auth0/lock

- lib/i18n/index.js
The danish translation was not included in the dictionary.
> Added da.json to dics_data in lib/i18n/index.js

- example/index.html
- example/index.less
- index.js
- test/tests.js
Added new event "signin" which allows us to modify the options before they're sent to auth0.js. This will allow us to use login_hint with ADFS.
> New event "signin" + update to latest styleguide

- standalone.js
This hack disable AMD while building "lock", then reenables.
Closes #172
> Solve the issue with AMD definitions inside our code

- index.js
- lib/css/themes/default.less
> Fix issue with ie9 inside div no render of labels

- index.js
- test/assets.tests.js
If the `hostname` is something like `foo.something.auth0.com` the assetsUrl should be `foo.something.auth0.com` not `cdn.auth0.com`.
> fix issue when the hostname is auth0 but with extra subdomains level

- lib/strategies/index.js
CSS issue here:
Other mode looks good (reuses `salesforce` style):
> Add salesforce-community support

- index.js
**without display=popup**
**with display=popup**
> Pass display='popup' for popup facebook strategy

- lib/mode-signin/index.js
- support/development-demo/index.html
> Add an 'enterprise ready' event

- LICENSE
- README.md
Adds author and license info to the readme. Updates license file.
Fixes https://github.com/auth0/lock/issues/284
> Update license and readme

- i18n/he.json
did a mistake, sorry i added a comment inside the json file which is invalid..
removed it.
> remove comment

- i18n/da.json
It said "Show All" in danish where the english translations says "Not your account?".
> More descriptive message for "Not your account?"

- bower.json
> Ignore test dir in bower.json

- lib/gravatar/index.js
- test/gravatar.tests.js
So they look nice in Retina screens.
> Use bigger Gravatars

- README.md
- package.json
- src/connection/database/actions.js
- src/connection/database/reset_password.jsx
- src/connection/database/reset_password_pane.jsx
- src/connection/enterprise/actions.js
- src/connection/passwordless/actions.js
- src/core/actions.js
- src/core/index.js
- src/core/remote-data/actions.js
- src/core/web_api.js
- src/engine/automatic.js
- src/quick-auth/actions.js
- Stop fetching the profile after a successful login in redirect mode
- Upgrade auth0.js to stop fetching the profile in popup mode
> Don't fetch profile automatically after login

- css/index.styl
- test/helper/ui.js
- Better handling of long login and sign up tabs labels
- Font styles for last database login
- Password strength subitems indentation
> Minor UI fixes

- package.json
@gnandretta fixes https://github.com/auth0/lock/issues/406. Upgrades to react 15 rather than move it to peer dependencies as discussed here: https://github.com/auth0/lock/issues/406#issuecomment-222999828
> Upgrade to react 15

- src/core/actions.js
- src/core/index.js
- Removes `redirect_error` event.
- Adds `authorization_error` event which is triggered in both redirect and popup mode.
> Authorization error

- package.json
- src/core/remote_data.js
- src/sync.js
Log a warning if we suspect that CORS wasn't configured.
> CORS warning

- src/core.js
- src/core/actions.js
- src/utils/cdn_utils.js
Use `Auth0` global constructor instead of lock's `getClient` method.
> Expose Auth0

- .github/ISSUE_TEMPLATE.md
> Add Issue template

- css/index.styl
Added new design tabs to web and mobile web
> New design tabs

- src/ui/input/email_input.jsx
- src/ui/input/username_input.jsx
- test/helper/ui.js
The onInput event introduced in 2f0661 doesn't work well with IE 10.
> Fix email input in IE 10

- css/index.styl
- src/ui/box/button.jsx
> Use tabs for log in and sign up

- src/i18n/cn.js
Please review and deliver this Chinese translation. Really in need.
> Chinese translation of lock

- support/design/index.js
Update the overridden function that simulates retrieving the client settings to use the new format.
> Fix design page

- support/design/index.js
Add missing parameter to the overridden function that simulates logging in.
> Fix login in design page

- src/i18n/en.js
- src/i18n/es.js
- src/i18n/it.js
- src/i18n/pt-br.js
- src/i18n/ru.js
- src/ui/box/container.jsx
- test/acceptance_test_utils.js
- test/helper/ui.js
Fixed Lock to work with XHTML applications (`application/xhtml+xml` Content-Type).
> XHTML compatibility fixes.

- scripts/ci.sh
We need the semver bin available.
> Move npm install to the top of ci script

- src/core/web_api.js
fix issue https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/issues/30
> Decode window.location.href before parsing hash

- css/index.styl
Fixed issue with ionic2 page scroll
Closes #532
> fixed ionic page scroll

- css/index.styl
- support/design/modal.html
Fixed signup terms checkbox overlays password field on small devices
Closes #525
> Fix checkbox terms

- css/index.styl
Fixes https://github.com/auth0/lock/issues/617
> Fixes for 10.3.0 regression

- src/i18n/zh-tw.js
Translate from zh.js to zh-tw.js for Traditional Chinese(Taiwan)
> add: i18n/zh-tw.js

- src/i18n/en.js
Fixes a minor misspelling. It jumped right out at me since I am currently integrating Auth0 with Active Directory.
> Fix typo in the word "corporate"

- src/connection/enterprise/actions.js
> Fix [v10.4.0] Cannot read property 'get' of undefined. #658

- src/core/client/settings.js
- src/core/index.js
- src/core/remote_data.js
- src/core/tenant/index.js
- src/core/tenant/settings.js
Added `__useTenantInfo` for the opt in. If `__useTenantInfo === false` (default) it will continue to use the client info
> Support for new Tenant info

- src/ui/input/password_input.jsx
> Password field shouldn't show error message immediately (on focus)

- src/core/actions.js
> 'TypeError: next is not a function' when closing social connection popup

- src/engine/classic.js
> Disabled username verification for prefill

- src/core/index.js
- src/core/tenant/index.js
- src/core/tenant/settings.js
Tenant info url built process
Fix casing
> Tenant info fixes

- src/ui/input/email_input.jsx
Focused on show email layout for keyboard in mobile browsers
> "Email" type for email input

- src/connection/enterprise/quick_auth_screen.jsx
- src/ui/pane/quick_auth_pane.jsx
> Fix: Single saml connection with no domain shows undefined in button

- src/ui/input/username_input.jsx
found this when writing protractor tests
> removed whitespace from input name

- src/quick-auth/actions.js
> Send login_hint when detecting previous session

- src/connection/enterprise.js
- src/connection/enterprise/actions.js
- src/connection/enterprise/hrd_screen.jsx
- src/core/index.js
Closes #713 and also closes #543
> Added flag defaultADUsernameFromEmailPrefix

- src/core.js
- src/core/actions.js
> Add events validation and fail if it is not a valid one

- src/core/web_api.js
- src/i18n/en.js
- src/i18n/es.js
> Added new error code: session_missing

- src/core/actions.js
- src/field/index.js
> Hide errors after close lock

- package.json
- src/core/web_api.js
> allow to override tenant + issuer and pass to auth0.js

- src/core/index.js
- src/core/web_api/legacy_api.js
- Delete the stored transaction info in legacy mode
- Fix default responseType behaviour
> Fix to comply legacy behaviour

- package.json
> Fix casing of null in IE (bumping auth0.js version)

- src/i18n/ca.js
"with" translation error --> "amb"
> Update ca.js - "with" translation error

- src/connection/database/index.js
> Clear invalid fields on screen change

- package.json
- src/core/web_api.js
- src/core/web_api/legacy_api.js
- src/core/web_api/p2_api.js
Should change auth0.js version
> inject cordova plugin and force popup/sso in cordova or electron

- src/sync.js
> Fix spelling of occurred

- package.json
- src/__tests__/core/web_api/__snapshots__/legacy_api.test.js.snap
- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/__tests__/core/web_api/legacy_api.test.js
- src/__tests__/core/web_api/p2_api.test.js
- src/core/web_api/helper.js
- src/core/web_api/legacy_api.js
- src/core/web_api/p2_api.js
> Cleaning params sent to auth0js

- src/core/loading_screen.jsx
This should improve speed perception (https://github.com/auth0/lock/issues/840)
> Reducing time to unpin loading pane

- package.json
> Update node engine restriction

- README.md
Add Japanse and link to all supported languages.
> Add Japanese to the supported languages list.

- src/i18n/fr.js
> Fix some french translations.

- src/ui/input/username_input.jsx
> disable autoCorrect and spellCheck in the username input

- src/connection/database/actions.js
- src/connection/passwordless/actions.js
- src/core/index.js
- src/field/email.js
- src/ui/box/chrome.jsx
- src/ui/box/container.jsx
- src/ui/box/global_message.jsx
> Add support for success and error messages to be in HTML

- css/index.styl
- src/__tests__/engine/classic/__snapshots__/sign_up_screen.test.jsx.snap
- src/__tests__/engine/classic/sign_up_screen.test.jsx
- src/__tests__/field/__snapshots__/social_buttons_pane.test.jsx.snap
- src/__tests__/field/social_buttons_pane.test.jsx
- src/engine/classic/sign_up_screen.jsx
- src/field/social/social_buttons_pane.jsx
> disable social buttons when terms were not accepted on sign up

- src/core/index.js
> Throw an error when audience is used without oidcConformant flag

- package.json
- yarn.lock
> Upgrade auth0js to v8.5.0

- css/index.styl
> Fixed scrolling on mobile in landscape mode

- src/i18n/cs.js
Fixed typo: vas@prikad.cz -> vas@priklad.cz
> Fixed typo in cs.js

- package.json
> package.json: ~ range allowed for auth0-js dep

- css/index.styl
affected on mobile view and fixed:
> Removed extra scroll on mobile view

- src/core/web_api/helper.js
- src/quick-auth/actions.js
> Fix custom connection scopes

- src/core/web_api/legacy_api.js
> Fixing empty popup on signup

- src/connection/enterprise.js
fix https://auth0.zendesk.com/agent/tickets/25148
> Set the username to the previously used email when toggling hrd

- src/__tests__/field/__snapshots__/password_pane.test.jsx.snap
- src/field/password/password_pane.jsx
> Fix spacing using custom signup fields

- src/__tests__/core/sso/__snapshots__/last_login_screen.test.jsx.snap
- src/__tests__/core/sso/last_login_screen.test.jsx
- src/core/sso/last_login_screen.jsx
> Fix custom theme for custom connections

- README.md
Missing info as reported in https://github.com/auth0/lock/issues/1128
> Adding readme entry about popup mode and oidc

- .vscode/settings.json
- README.md
- package.json
- src/__tests__/core/sso/__snapshots__/last_login_screen.test.jsx.snap
- src/__tests__/core/sso/last_login_screen.test.jsx
- src/__tests__/core/web_api/__snapshots__/legacy_api.test.js.snap
- src/__tests__/core/web_api/legacy_api.test.js
- src/connection/enterprise/actions.js
- src/core.js
- src/core/index.js
- src/core/remote_data.js
- src/core/sso/data.js
- src/core/sso/index.js
- src/core/sso/last_login_screen.jsx
- src/core/web_api.js
- src/core/web_api/legacy_api.js
- src/core/web_api/p2_api.js
- src/engine/classic.js
- src/engine/classic/login.jsx
- support/index.html
- test/connection_pick.ui.test.js
- test/enterprise_quick_auth.ui.test.js
- test/helper/sso_data.js
- test/helper/ui.js
- test/layout.ui.test.js
- test/mfa_ro.ui.test.js
- test/out-of-date/index.js
- test/regression.test.js
- test/sign_up_terms_agreement.ui.test.js
- yarn.lock
> Revert old v11 design changes

- Gruntfile.js
- README.md
- package.json
- src/__tests__/core/sso/__snapshots__/last_login_screen.test.jsx.snap
- src/__tests__/core/sso/last_login_screen.test.jsx
- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/__tests__/core/web_api/p2_api.test.js
- src/connection/enterprise/actions.js
- src/core.js
- src/core/actions.js
- src/core/index.js
- src/core/remote_data.js
- src/core/sso/data.js
- src/core/sso/last_login_screen.jsx
- src/core/web_api.js
- src/core/web_api/p2_api.js
- src/engine/classic.js
- src/engine/classic/login.jsx
- src/quick-auth/actions.js
- support/index.html
- test/helper/ui.js
- test/layout.ui.test.js
- yarn.lock
- exposes `checkSession` method
- removes `oidcConformant` flag
- don't use legacy apis
- make "last time you login screen" work with oidc flows
> Actual v11 features

- src/i18n/no.js
Please find the translation for Norwegian.
> Norwegian translation

- README.md
> Fix scope documentation

- src/connection/enterprise.js
fix https://github.com/auth0/lock/issues/1270
> Add enterprise mapping to the auth0-oidc strategy

- src/quick-auth/actions.js
fix https://github.com/auth0/lock/issues/1296
> Fixing IE lack of support for `includes`

- src/i18n/de.js
* I used the formal way of addressing people, i.e. "Sie" instead of colloquial "Du"
* I am not able to see the effect of breaks inside the text (`<br>`), if it looks OK etc.
> Fixed German translations

- CHANGELOG.md
- README.md
- bower.json
- package.json
- yarn.lock
fix https://github.com/auth0/lock/issues/1312
> Release v11.5.1

- README.md
- src/connection/database/actions.js
> Emit signup error

- src/core.js
> Add signup error to valid events

- README.md
> Fix link to auth0 documentation

- src/i18n/da.js
fix https://github.com/auth0/lock/issues/1337
> Fix danish translation

- src/__tests__/core/__snapshots__/actions.test.js.snap
- src/__tests__/core/actions.test.js
- src/core/actions.js
> Show spinner when doing quick auth

- css/index.styl
> Fix rendering issue on iOS devices

- src/i18n/tr.js
Related discussions => https://community.auth0.com/t/turkish-language-correction-request-for-lock-login-screen/11750
> Update "yada" with "veya"

- src/i18n/ja.js
Fixed two-byte character in Japanese. Please review/merge 🙇
> Don’t use two-byte character

- src/ui/box/chrome.jsx
- test/helper/ui.js
fix https://github.com/auth0/lock/issues/1393
> Fix IE submit button display:initial issue

- src/i18n/nn.js
Added an i18n file for the Norwegian second language Nynorsk.
> Added an i18n file for the Norwegian Nynorsk language

- src/__tests__/field/__snapshots__/vcode.test.js.snap
- src/__tests__/field/vcode.test.js
- src/field/vcode.js
fix https://github.com/auth0/lock/issues/1387
> Trimming vcode input

- README.md
> Made change in README file

- README.md
fixed capitalization of the term "URL" in README
> Capitalized "URL"

- src/i18n/de.js
- src/i18n/en.js
improved German translation
a few small improvements to bring the German translation closer to the English original and to increase consistency, such as:
1. email address is now E-Mail-Adresse, which is different from email message (E-Mail).
2. Multifactor is now Multifaktor-Authentifizierung everywhere
3. "Es tut uns leid" is placed in all messages, that have a "we're sorry" in English.
4. sentLabel is now correct.
5. Corporate is now "geschäftlich" everywhere instead of a mix of "Unternehmen" and "geschäftlich".
6. changed lines to reflect same ordering as English
added a minor comma to the English original
> improved German translation

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Improved the issue template and added a PR template.
> Change issue template, add PR template

- README.md
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
> Fixed few grammatical errors in README

- README.md
fix author URL directing to 404 page.
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should …
> fix Author URL

- package.json
- yarn.lock
Fix https://github.com/auth0/lock/issues/1523
> Fix IE10 script error

- package.json
- yarn.lock
This check will prevent issues like [this](https://github.com/auth0/lock/issues/1523) from happening again.
> Add JS incompatibility check during tests

- src/i18n/tr.js
> Fixes in Turkish translation

- css/index.styl
- src/__tests__/engine/classic/__snapshots__/login.test.jsx.snap
- src/__tests__/engine/classic/__snapshots__/sign_up_screen.test.jsx.snap
- src/engine/classic/login.jsx
- src/engine/classic/sign_up_screen.jsx
- src/engine/passwordless/social_or_email_login_screen.jsx
- src/engine/passwordless/social_or_phone_number_login_screen.jsx
- src/ui/box/chrome.jsx
- support/index.html
This PR fixes
- Inconsistent padding across screens after #1547 
- IE glitches after we added flexbox in #1539 (the actual issues were: https://github.com/philipwalton/flexbugs#flexbug-3, https://github.com/philipwalton/flexbugs#flexbug-4 and https://github.com/philipwalton/flexbugs#flexbug-6)
> Fix IE flexbox bugs

- README.md
> Clarifies default validator behavior for additionalSignupFields

- src/i18n/he.js
> Add hebrew support

- package.json
- yarn.lock
Bumping Auth0.js dependency
https://github.com/auth0/auth0.js/pull/899
> Upgrade Auth0.js with fix for storage inside the Hosted Login Page

- package.json
- yarn.lock
Upgrading AUth0.js with this change: https://github.com/auth0/auth0.js/pull/895
> Upgrade Auth0.js to trim email, username and phoneNumber on every request

- css/index.styl
@luisrudge Can you please take a look at this? I think it solves the scrolling  issues
> Fixes scrolling issues

- src/connection/enterprise.js
This adds a new entry to the enterprise strategies to allow connections with strategy 'oidc'
> Add label for "oidc" strategy

- css/index.styl
> Fix IE11 height

- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/__tests__/core/web_api/p2_api.test.js
- src/core/web_api/helper.js
- src/core/web_api/p2_api.js
Fix telemetry with overrides and inside ULP
> Fix telemetry

- src/i18n/bg.js
- Adds a translation for Bulgarian (bg)
- support ticket 00426179
You need to be proficient in the Bulgarian language.
> Add translation for Bulgarian (bg).

- src/core/remote_data.js
> Improve ssodata warning message

- src/i18n/ms.js
> Malay language translation is added

- src/i18n/id.js
- Indonesian translation is added
> Indonesian translation is added

- src/i18n/uk.js
- Ukrainian translation is added
> ukrainian translation is added

- src/i18n/sr.js
- Serbian translation is added
> serbian translation is added

- src/i18n/lv.js
- Latvian translation is added
> Latvian translation is added

- package.json
Since we upgraded the cdn uploader, we can start uploading the digest as well.
> Add cdn digest

- package.json
- yarn.lock
This upgrades our cdn uploader to fix a bug that caused new builds to override previous uploaded files.
> Fix cdn upload

- src/utils/cache.js
Adapt utils/cache to handle case where key is missing without error.
This was causing uncaught promise rejections at random moments.
Fixes https://github.com/auth0/lock/issues/1599 , but may not handle the root cause.
> handle missing key in cache without error

- package.json
- yarn.lock
Changelog: https://github.com/auth0/auth0.js/blob/master/CHANGELOG.md#v9110-2019-06-25
> Upgrade Auth0.js to 9.11.0

- src/i18n/hu.js
- fixed a hungarian translation about the password strength
> fixed a hungarian translation about the password strength

- src/ui/box/multisize_slide.js
Fixes #1700
Remove call to undefined function `cb`.
No visual changes  - except no error in console.
> Fix call to undefined function cb

- src/i18n/hu.js
Added a hungarian translation for `social_signup_needs_terms_acception` which was introduced in #1733 
> added hungarian transalation for social_signup_needs_terms_acception

- README.md
> [SDK-1141] Altered readme samples to remove ref to localstorage

- src/i18n/pt.js
Fixed the "_user_" translation to pt-PT.
usuário: pt-BR
utilizador: pt-PT
> Fix translation pt-PT

- src/i18n/cs.js
This PR updates various Czech language strings.
Raised through internal ESD.
> Update cs.js - plural adjustments

- src/field/username.js
> Typo fix in username.js

- DEVELOPMENT.md
This adds a file to demonstrate basic development options with the SDK.
> Add a basic DEVELOPMENT file to explain common scenarios

- CHANGELOG.md
- README.md
- bower.json
- package.json
- yarn.lock
**Fixed**
- [SDK-1738] Remove subtle transition on header element [\#1892](https://github.com/auth0/lock/pull/1892) ([stevehobbsdev](https://github.com/stevehobbsdev))
Also bumped `auth0-js` to [v9.13.4](https://github.com/auth0/auth0.js/releases/tag/v9.13.4)
[SDK-1738]: https://auth0team.atlassian.net/browse/SDK-1738
> Release v11.24.5

- DEVELOPMENT.md
Fix markdown formatting for `DEVELOPMENT.md`
> Fix DEVELOPMENT.md formatting

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Added**
- [CAUTH-423] Add captcha in the sign-up flow [\#1902](https://github.com/auth0/lock/pull/1902) ([jfromaniello](https://github.com/jfromaniello))
**Changed**
- [CAUTH-511] improve error handling on missing captcha [\#1900](https://github.com/auth0/lock/pull/1900) ([jfromaniello](https://github.com/jfromaniello))
**Fixed**
- [SDK-1284] Fix for "growing" tabs when repeatedly clicked [\#1904](https://github.com/auth0/lock/pull/1904) ([stevehobbsdev](https://github.com/stevehobbsdev))
[CAUTH-423]: https://auth0team.atlassian.net/browse/CAUTH-423
[CAUTH-511]: https://auth0team.atlassian.net/browse/CAUTH-511
[SDK-1284]: https://auth0team.atlassian.net/browse/SDK-1284
> Release v11.26.0

- src/field/captcha/captcha_pane.jsx
Fix an issue introduced by #1902 . Remove the extension from the file.
reported in #1906
> fix issue #1906 - remove extension from import

- CHANGELOG.md
- README.md
- bower.json
- package.json
[Full Changelog](https://github.com/auth0/lock/compare/v11.26.0...v11.26.1)
**Fixed**
- fix issue #1906 - remove extension from import [\#1907](https://github.com/auth0/lock/pull/1907) ([jfromaniello](https://github.com/jfromaniello))
> Release v11.26.1

- CHANGELOG.md
- README.md
- bower.json
- package.json
- src/__tests__/connection/enterprise/__snapshots__/hrd_screen.test.js.snap
- src/__tests__/connection/passwordless/__snapshots__/ask_vcode.test.jsx.snap
**Security**
- [SEC-512] Replace usage of i18n.html with i18n.str in Passwordless verification code UI ([stevehobbsdev](https://github.com/stevehobbsdev))
[SEC-512]: https://auth0team.atlassian.net/browse/SEC-512
> Release v11.26.3

- package.json
- yarn.lock
This is a dependency upgrade PR for an upcoming release:
* Upgrade dependencies to latest according to semver (including [auth0-js](https://github.com/auth0/auth0.js/releases/tag/v9.14.0))
* `npm audit fix`
> Dependencies

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Changed**
- Better flash error messages on incorrect, empty fields. [\#1923](https://github.com/auth0/lock/pull/1923) ([saltukalakus](https://github.com/saltukalakus))
- [SDK-1946] Update Basecamp logo [\#1922](https://github.com/auth0/lock/pull/1922) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
- [SDK-1911] Always use UsernamePane when using custom resolver [\#1918](https://github.com/auth0/lock/pull/1918) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Security**
- Routine dependency updates [\#1924](https://github.com/auth0/lock/pull/1924) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Add license scan report and status [\#1920](https://github.com/auth0/lock/pull/1920) ([fossabot](https://github.com/fossabot))
[SDK-1946]: …
> Release 11.27.0

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Changed**
- Update cs.js [\#1944](https://github.com/auth0/lock/pull/1944) ([HopXXII](https://github.com/HopXXII))
**Fixed**
- [ESD-10361] Fix password strength popup overflow issue [\#1949](https://github.com/auth0/lock/pull/1949) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [ESD-10373] Fix rendering of Lock inside popup on first open [\#1948](https://github.com/auth0/lock/pull/1948) ([stevehobbsdev](https://github.com/stevehobbsdev))
[ESD-10361]: https://auth0team.atlassian.net/browse/ESD-10361
[ESD-10373]: https://auth0team.atlassian.net/browse/ESD-10373
> Release 11.27.2

- CHANGELOG.md
- README.md
- bower.json
- package.json
> Release v11.28.1

- yarn.lock
Updates dependencies in the lock file by running `npm audit` and then using `yarn import` to import the changes and regenerate the lock file.
> Run npm audit and reimport yarn lock file

- src/field/captcha/recaptchav2.jsx
This fix an issue that prevent the recaptcha popup to show on small screens.
> [ESD-12716] fix issue with recaptcha in mobile

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Added**
- [SDK-2412] Add event for SSO data fetch [\#1977](https://github.com/auth0/lock/pull/1977) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SDK-2306] Add login and signup hooks [\#1976](https://github.com/auth0/lock/pull/1976) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
- [ESD-12716] fix issue with recaptcha in mobile [\#1978](https://github.com/auth0/lock/pull/1978) ([jfromaniello](https://github.com/jfromaniello))
- Fixes typo "assests" to "assets" [\#1975](https://github.com/auth0/lock/pull/1975) ([morkro](https://github.com/morkro))
- Remove line breaks from passwordless vcode entry instructions [\#1974](https://github.com/auth0/lock/pull/1974) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Remove padding from screen tabs …
> Release v11.29.0

- src/field/captcha/recaptcha.jsx
Fix recaptcha on mobile when using a different language.
- ESD-12716
> [ESD-12716]fix recaptcha on mobile when lang is not English

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Added**
- Recaptcha Enterprise support [\#1986](https://github.com/auth0/lock/pull/1986) ([akmjenkins](https://github.com/akmjenkins))
**Fixed**
- [ESD-12716]fix recaptcha on mobile when lang is not English [\#1988](https://github.com/auth0/lock/pull/1988) ([jfromaniello](https://github.com/jfromaniello))
[ESD-12716]: https://auth0team.atlassian.net/browse/ESD-12716
> Release v11.30.0

- CHANGELOG.md
- README.md
- bower.json
- package.json
- yarn.lock
> Prepare v11.30.3

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Fixed**
- Updated Dutch translations [\#2013](https://github.com/auth0/lock/pull/2013) ([erombouts](https://github.com/erombouts))
> Release 11.30.4

- README.md
> Add `signUpFieldsStrictValidation` description to the readme

- .gitignore
- package.json
- yarn.lock
This PR updates several dependencies to their latest, some fix Snyk issues.
Also includes an update to `auth0-js` and `idtoken-verifier` for the
`crypto-js@4` update.
> Dependency update

- .circleci/config.yml
- scripts/ci.sh
Makes use of our script to publish to npm/github when a new release PR is done.
> Automate package publishing

- .circleci/config.yml
- .shiprc
* Configure a0/ship to build the project and force-add the build folder on generating the release PR. This should fix an issue with the build assets not appearing in the published release
* Remove dependency on `browserstack` circle job before doing the release. This will be added back once the tests are made more reliable in the near future. Instead, we can do a manual check at the point when reviewing the release PR.
#2036
> Release configuration

- src/i18n/de.js
Update Germany translation for loginWithLabel to comply with Apple's Design Guidelines. The standard translation got rejected in the Appstore Review:
> Your app offers Sign in with Apple as a login option but does not use the appropriate Sign in with Apple button design, placement, and/or user interface elements. Specifically:
>
> - The  Sign in with Apple says “ANMELDEN MIT APPLE” but should use the following localized version: “Mit Apple anmelden”.
>
> Next Steps
>
> Please revise the Sign in with Apple buttons in your app so that they are compliant with the App Store Review Guidelines and the Sign in With Apple Human Interface Guidelines.
For more details see https://developer.apple.com/documentation/sign_in_with_apple/displaying_sign_in_with_apple_buttons_on_the_web?preferredLanguage= …
> align german loginWithLabel translation with Apple Guidelines

- src/engine/classic/sign_up_pane.jsx
This PR moves the captcha UI below the additional signup fields for a nicer UI experience.
Fixes #2118
> Move captcha pane below additional signup fields in UI

- Makefile
> Use makefile

- README.md
> Remove FAQ reference from README

- package.json
to make homepage visible for example in VSCode on hover:
> homepage added to package.json

- CHANGELOG.md
- README.md
- package.json
Lock is now built using React 18, which resolves a number of security vulnerabilities and improves performance. If you encounter any issues relating to this upgrade, please [submit a bug report](https://github.com/auth0/lock/issues/new?assignees=&labels=bug+report,v12&template=report_a_bug.md&title=).
Despite the major version bump, **v12 is completely API-compatible with v11**.
**Changed**
- Upgrade to React 18 [\#2209](https://github.com/auth0/lock/pull/2209) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Upgrade to Webpack 5 [\#2213](https://github.com/auth0/lock/pull/2213) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Various dependency bumps [see the full changelog](https://github.com/auth0/lock/compare/v11.35.0...v12.0.0)
> [SDK-3874] Release v12.0.0

- Makefile
> Use yarn publish

- CHANGELOG.md
- README.md
- package.json
**Changed**
- FDR-487 - feat: update microsoft button [\#2259](https://github.com/auth0/lock/pull/2259) ([jamescgarrett](https://github.com/jamescgarrett))
> Release v12.0.1

- Makefile
Backports the fixes from #2248 and #2246 to fix the CDN publish step on Jenkins
> Backport build fixes for Jenkins CDN step

- CHANGELOG.md
- README.md
- package.json
**Changed**
- Slight tweaks to Captcha input component handler methods + refresh button mask [\#2272](https://github.com/auth0/lock/pull/2272) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
- Fix for when component is undefined on unmount [\#2271](https://github.com/auth0/lock/pull/2271) ([codetheweb](https://github.com/codetheweb))
> Release v12.0.2

- package.json
- yarn.lock
Include [`events`](https://www.npmjs.com/package/events) in package dependencies. This dependency is already hoisted from `webpack` and we import it, but it does break in certain circumstances as it's not included as a first-class dependency.
Closes #2290
> chore: add 'events' to dependencies

- .semgrepignore
This PR adds a a semgrep ignore file to the repository, to avoid false warnings on examples and playground code.
N/A
> test: Add .semgrepignore

- package.json
- yarn.lock
uglify-js is unused and can be safely removed. it was used in the past in Gruntfile.js ("UglifyJsPlugin").
> chore(deps-dev): removed unused uglify-js dependency

- CHANGELOG.md
- README.md
- package.json
**Added**
- Added support for hCaptcha and Friendly Captcha [\#2387](https://github.com/auth0/lock/pull/2387) ([DominickBattistini](https://github.com/DominickBattistini))
**Changed**
- WelcomeMessage header text marked as heading [\#2373](https://github.com/auth0/lock/pull/2373) ([piwysocki](https://github.com/piwysocki))
> Release v12.1.0

- CHANGELOG.md
- package.json
Fixes the version to be released, as the previous version is 12.3.0.
> Fix version to be released

- .github/workflows/semgrep.yml
- .github/workflows/snyk.yml
ci: changed the trigger from pull_request_target to pull_request for better security
> ci: changed the trigger from pull_request_target to pull_request for better security

- .gitignore
- Makefile
- chore: update .gitignore and Makefile for Puppeteer cache and config directories
> chore: update .gitignore and Makefile for Puppeteer cache and config directories
