- i18n/de.json
Replace the word ```Kennwort``` with ```Passwort``` to be more consistent, add one missing character and streamline the ```serverErrorText```.
> fix(i18n): fix some minor german translation inconsistencies

- index.js
The unnecessary work of finding the last script tag can lead to breakage when there are no script elements on the page
> Just append to the document head

- i18n/en.json
- lib/css/themes/default.less
- lib/mode-reset/reset.ejs
- lib/mode-signin/signin.ejs
- lib/mode-signup/signup.ejs
This allows setting a footer that is consistent across all modes, not just `signup`.
> Add footerText to signin and reset modes

- index.js
- lib/mode-reset/index.js
- lib/mode-signin/index.js
- lib/mode-signup/index.js
- lib/options-manager/index.js
This will improve the SSO experience when a user enters their email address for which the email suffix has been configured on a connection:
- Signup and Reset buttons are hidden when we are in HRD mode
- If you enter an SSO enabled email address on the SignUp or Reset panel, the Lock will navigate back to SignIn, enter your email address there and trigger HRD
- If you then edit your email address and no longer have an SSO enabled email address, you'll be redirected back to the previous panel (SignUp or Reset). This is required when we start the Lock in SignUp mode only for example
> Improve SSO experience

- index.js
- lib/errors/ValidationError.js
- lib/mode-kerberos/index.js
- lib/mode-loggedin/index.js
- lib/mode-reset/index.js
- lib/mode-signin/index.js
- lib/mode-signup/index.js
- support/development-demo/index.html
- test/reset.tests.js
- test/signup.tests.js
- test/tests.js
This PR completes the lifecycle of events for our modes: `signin`, `signup`, `reset`.
- Close auth0/lock#82
The states added are: `ready`, `submit`, `success` and `error`.
Which will generate events like
```js
lock.on('signup ready', function () {})
lock.on('signup submit', function () {})
lock.on('signup success', function () {})
lock.on('signup error', function () {})
// ... same for signin and reset
```
> Added Lifecycle events

- index.js
\### Briefing
It has come to our knowledge the need of users to establish when the lock was hidden by it's own action or by a close action.
This PR adds a `close` event triggered when the X is clicked by the users. It also completes some of the events added for auth0/lock#82 completing a lifecycle.
- Close auth0/lock#188
> Add close event for when the user clicks the X button

- Gruntfile.js
- i18n/en.json
- index.js
- package.json
- support/development-demo/index.html
- Add a new dict option `signin:unauthorizedErrorText` defaulting to `Access denied.`. Thanks @pose
- Verified custom error messages from Database connections
- Verified custom error messages from Social connections. Thanks @siacomuzzi for the server implementation
> Add support for custom error messages from rules

- README.md
- examples/webpack/webpack.config.js
I actually didn't find the webpack instructions because I assumed there weren't any after I scrolled past the Browserify section, and ended up wasting a little bit of time.
This improves the organization of that section of the README a bit and will hopefully prevent other people from making the same mistake in the future.
This also improves the webpack example a little bit by restricting the scope of the transforms to just the `auth0-lock` package.
> Improve webpack instructions

- README.md
- examples/webpack/package.json
- examples/webpack/webpack.config.js
This speeds up incremental builds in webpack for users a bit; previously the files were not cacheable, and had to be re-built by webpack on incremental builds even if they didn't change.
> Use cacheable loaders in webpack

- lib/options-manager/index.js
When the connection is unknown and SSO is enabled `LoggednPanel` is displayed without any buttons, as reported in #244.
> Don't show last login for unknown connections

- README.md
- examples/webpack/webpack.config.js
This is a minor fix to the webpack example (and the corresponding doc in the project readme) that makes it more copy-pastable into peoples' existing projects.
For example, the previous example would not work if a project also had [json](https://www.npmjs.com/package/json) in their `node_modules` directory (which is a different module than [json-loader](https://www.npmjs.com/package/json-loader)).
This is a great project, thanks for making it available! :smile:
> Fix webpack example

- i18n/en.json
Commit b94f24ad047e4485ed1decbcf2c6a4f762281aec introduced a new translation `sigin:userBlockedErrorText` and by convention we add it to the reference `en` dictionary. It was intentionally left blank to show the message returned by the API by default.
> Add reference sigin:userBlockedErrorText translation

- index.js
- lib/mode-kerberos/index.js
- lib/mode-loggedin/index.js
- lib/mode-reset/index.js
- lib/mode-signin/index.js
- lib/mode-signup/index.js
If something goes wrong during the login, the _sing in_ panel should be displayed instead of the _sign up panel_. See #257.
> Improve error handling when logging in automatically

- lib/i18n/index.js
When a dict option was provided with a language that wasn't supported, the dictionary was `undefined` and the Lock crashed before opening.
This change falls back to the default dictionary when the dictionary for the specified language can't be found.
> Stop crashing when providing an unknown dict

- index.js
A new `stage` environment has been added and Lock is failing to obtain the client settings from the CDN because the assetsUrl is incorrect.
> Consider stage subdomain when building assets url

- lib/i18n/dicts.js
The dict was already provided in a previous PR (#226) but it wasn't exported.
> Add Thai (th) language

- index.js
- lib/header/lock-header.ejs
- lib/options-manager/index.js
- package.json
Adds support for electron:
- Allows to override `Auth0.prototype.openWindow` (see the details in the PR linked above)
- Loads the default icon correctly when `window.location.protocol` is `"file:"`, which is the case for Electron.
> Electron support

- README.md
- examples/webpack/package.json
- package.json
- Upgraded brfs version, because it doesn't work with webpack (see #301). Since lock 8.2.0 it's included as a regular dependency and is the one that webpack picks up.
- Upgraded lock version in webpack example and updated instructions in README.
> Fix webpack bundle

- .zuul.yml
- bin/deploy
- index.js
- lib/html/lock-footer.ejs
- package.json
- Use the "support" tag when publishing the npm module, otherwise it will be installed with `npm install auth0-lock` because it will be the latest. We want the last release in the 9 branch to be installed by default.
- Upgrade to ngrok 2 so test can keep running.
- Update telemetry info.
- Add campaign params to badge link.
> V8 deploy script fix + backports

- .zuul.yml
- bin/deploy
- index.js
- lib/html/lock-footer.ejs
- package.json
- Use the "support" tag when publishing the npm module, otherwise it will be installed with `npm install auth0-lock` because it will be the latest. We want the last release in the 9 branch to be installed by default.
- Upgrade to ngrok 2 so test can keep running.
- Update telemetry info.
- Add campaign params to badge link.
> V7 deploy script fix + backports

- src/connection/database/actions.js
Fix decision to use email or username for db login. We need to consider the presence of enterprise connections. Even when the database connection allows to login with a username an email input
can be displayed.
> Fix database login

- lib/options-manager/index.js
Use optimised version of badge image.
From 8kb to 2kb.
> Use optimised version of our logo (badge)

- README.md
- src/core/index.js
- src/core/web_api.js
JSONP was used in some old IE versions that we no longer support
> Remove JSONP authentication suppport

- src/core/index.js
- test/layout.ui.test.js
Otherwise `hasOneConnection` and `hasOnlyConnections` that depend on the number of available connections will return invalid results because unknown connections are counted. This caused the display of a submit button with only social buttons when social and unknown connections were the only types available.
> Ignore unknown connections

- src/connection/database/actions.js
- src/connection/enterprise/actions.js
- src/connection/passwordless/actions.js
- src/core/actions.js
- src/core/index.js
- src/core/signed_in_confirmation.jsx
- src/field/index.js
- src/quick-auth/actions.js
- No longer invoke the auth callback if the error is already handled by Lock (like invalid user/pass)
- Removed form submission/login logic duplication across different connection types.
- Renamed some functions names that used "sign in" instead of "log in" for consistency.
> Invoke auth callback only on success

- README.md
- src/connection/social/index.js
- If only social connections are available, fallback to small buttons when there are more than five.
- If other connections are available, fallback to small buttons when there are more than three.
> Change socialButtonStyle option default

- src/connection/database/actions.js
- src/connection/database/index.js
- src/core.js
- src/core/actions.js
- src/core/index.js
- src/core/remote_data.js
- src/engine/automatic.js
- src/sync.js
The callback will be invoked when:
- A sync fails, except if it is for SSO data.
- Automatic login fails and the login screen is not allowed.
- No connection is available (because no connection is enabled in the dashboard or none of the `allowedConnections` is found).
- Can't found a screen to render (internal error).
- The `initialScreen` is not available for the enabled connections.
The way hooks are implemented has been changed to avoid to swap the state twice in a row.
> Invoke callback with unrecoverable errors

- src/connection/database/index.js
- src/core.js
- src/core/actions.js
- src/core/index.js
- src/field/index.js
- src/index.js
- src/passwordless.js
This adds the following events:
- `show`: emitted when Lock is shown. Has no arguments.
- `hide`: emitted when Lock is hidden. Has no arguments.
- `error`: emitted when there is an unrecoverable error, for instance no connection is available. Has an `Error` instance as the only argument.
- `authenticated`: emitted after a successful authentication. Has the authentication result provided by auth0.js as the only argument.
- `redirect_error`: emitted when the authentication fails after redirecting to Auth0, for instance a rule error. Has the error provided by auth0.js as the only argument.
It also removes the callback argument from the constructor. The `authenticated` and `redirect_error` must be used instead.
**Before**
```js
var lock = new Auth0Lock(cid. domain, opts, function (error, …
```
> Add events

- src/core.js
- src/core/actions.js
- src/store/index.js
This ensures all instances get a chance to listen to the authenticated events.
> Global auth events

- README.md
- src/field/custom_input.jsx
- src/field/index.js
- src/field/username/username_pane.jsx
- src/ui/input/text_input.jsx
The _validator_ function instead of returning a **bool** now returns an **object** with a required `valid` property and an optional `hint` property. The `valid` property is a bool which indicates whether or not the field is valid. The `hint` property is a string that will be displayed in the error hint.
```js
validator: function(code) {
return {
valid: code.length === 3, // required
hint: "Must have 3 chars" // optional
};
}
```
> Add hint support in additional field validator

- src/core.js
- src/core/actions.js
The `getClient` method is added to support some uncommon but valid use cases.
> Add getClient method and remove parseHash

- src/core/index.js
Event listener invocations were surrounded in a try/catch block to prevent errors in them to interfere with Lock behavior. As a consequence of this, errors didn't show up in the console log.
> Delay event emission

- .zuul.yml
- Gruntfile.js
- package.json
For some reason, we can't run test for more than 3 browsers in saucelabs. We can run IE tests individually until we find a better solution. (Couldn't find a way to give the zuul cmd more than one browser or an alternative .zuul.yml config file).
> Temp split browser tests

- src/ui/input/email_input.jsx
- test/helper/ui.js
When using `onChange` some events are skipped in IE11.
> Use onInput instead of onChange in EmailField

- src/ui/box.js
Otherwise when a container is removed we are not able to render in another container element with the same id.
> Remove cache for container elements

- src/ui/pane/quick_auth_pane.jsx
tl;dr The code for PropType validation function will be removed from production builds of React, so we need to let React know that we are wrapping its PropType.
The details are in https://facebook.github.io/react/warnings/dont-call-proptypes.html.
> Remove react warning

- Gruntfile.js
- package.json
It stopped working with new React versions.
> Remove livereactload

- README.md
- src/core/actions.js
- src/core/index.js
The event is fired after any lock attempt to parse the url's hash part. It is a low level event for cases where you need to know if there is a login result before initializing your application. It should not be used in conjunction with the `authenticated` and the `authorization_error` events
> Add hash_parsed event

- README.md
Just a tiny update to the README to clarify the situation where the required behaviour is support for both `username` entries (such as phone numbers) and `email`
> Clarify usernameStyle default behaviour

- src/core/web_api.js
Due to the recent change decoding the hash value, whenever a `decodeURIComponent(undefined)` is done, then the value passed to `auth0-js`'s parseHash() method would be `"undefined"`.
This change prevents possible errors or wrong assumptions inside that method.
> Change the default value for hash in WebApi.parseHash() internal method

- README.md
- src/core/client/settings.js
- src/core/index.js
- src/core/remote_data.js
- src/i18n.js
- support/design/index.js
Introduce `languageBaseUrl` and `cliengBaseUrl` in replacement of `assetsUrl`.
- The client will be fetched from `${clientBaseUrl}/${clientID}.js` and will default to the CDN url including the region (e.g. `https://cdn.eu.auth0.com/client`). The region is inferred from the `domain`.
- The language will be fetched from `${languageBaseUrl}/${lang}.js` and will default to the CDN without the region (e.g. `https://cdn.auth0.com/js/lock/${lockVersion}/`).
- The new options have priority over `assetsUrl`.
- If `assetsUrl` is provided, keep the current behavior: fetch client from `${assetsUrl}/client/${clientID}.js` and languages from `{assetsUrl}/js/lock/${lockVersion}/${language}.js`.
---
- Fixes auth0/lock#576
> Introduce clientBaseUrl and languageBaseUrl options to deprecate assetsUrl

- css/index.styl
- package.json
- src/ui/box/chrome.jsx
- src/ui/box/global_message.jsx
`global_message.jsx`'s code for componentWillEnter and componentWillLeave looked like quite a mess with the .style.this and .style.that.  This change lets the CSS do what it's good at and keeps the JS looking a bit cleaner in that file.
It also cuts down on a dependency.
> use ReactCSSTransitionGroup for global messages

- src/connection/enterprise.js
Improves handling of the format sent by the server using and AD connection with Kerberos authentication.
When connecting from a corporate network a user can choose to connect using Kerberos or certificate authentication. In any of these cases lock relies in information provided by the server to validate that the user is in a corporate network and to obtain the name and strategy of the connection associated with the network. 
However, the format of the information is flat inside the `sso` object and not in the connection format used in other cases. The fix manages the flat format and creates a temporary object with the known format to allow `KerberosScreen` to work as expected.
---
- Fixes auth0/lock#590
> Fixes corporate network connection usage

- src/core/index.js
Since the `emitEventFn` inherits from `EventEmitter` and custom errors are being emitted, the default `error` event will not be triggered.
This change checks if an `unrecoverable_error` is being emitted and throws it if there are no attached listeners.
An `unrecoverable_error` can be triggered for testing by turning off all Client Connections and trying to create an instance of Lock.
> Handle uncaught unrecoverable_error

- css/index.styl
- src/ui/box/chrome.jsx
> fixed loading unaligned with label submit

- src/core/client/index.js
- src/field/username.js
- src/field/username/username_pane.jsx
- src/i18n/da.js
- src/i18n/de.js
- src/i18n/en.js
- src/i18n/es.js
- src/i18n/fr.js
- src/i18n/hu.js
- src/i18n/it.js
- src/i18n/nb.js
- src/i18n/pt-br.js
- src/i18n/ru.js
- src/i18n/sv.js
- src/i18n/zh.js
After the introduction of the new feature for configuring username validation min/max values at Auth0 we required to handle those modifications within the Lock UI. Therefore:
1. If the validation settings is defined within the client info object, use those parameters (configured from the [Dashboard](https://manage.auth0.com/#/connections/database))
2. If validation settings is missing from within the client info settings, defaults to the current values `{min: 1, max: 15}`.
3. No validations are performed for `enterprise` connections, as it was the previous behavior.
> Add min/max username validation from client info settings

- src/ui/box/container.jsx
**Description:**
There is a bug in lock when Container is set to `container: "name"` and the `ESC` button is pressed, this error occurs:
```js
Uncaught TypeError: closeHandler is not a function - container.js:119
handleClose @ container.js:119
handleEsc @ container.js:128
EscKeyDownHandler.handler @ container.js:54
```
The lock has the  `container` UI option set to `true`, which should cause `closable` to change to `false` as well, as per the [#Customization](https://github.com/auth0/lock#customization) section in the docs - so this behavior should not be expected, since the lock is still expecting a function to handle close.
**Changes Proposed:**
- Add condition to only mount **Container** component with `EscKeyDownHandler` to `this.escKeydown` when a `closeHandler` prop exists.
- Add …
> Fix EscKeyDownHandler bug in Container when `closable` is false

- package.json
Bumping `blueimp-md5@2.3.1` which introduces a set of updates in the module loader.
- Fixes https://github.com/auth0/lock/issues/466
> Bump blueimp-md5@2.3.1

- src/i18n/nl.js
Based on following articles (in Dutch) the words _email_ and _emailadres_ are incorrect and should be translated as _e-mail_ and _e-mailadres_.
https://onzetaal.nl/taaladvies/email-e-mail
http://www.taaltelefoon.be/e-mailadres-emailadres
> Change the term email to e-mail and emailadres to e-mailadres

- src/core/actions.js
- src/core/index.js
- support/index.html
- test/helper/ui.js
- test/show_with_flash_message.test.js
- test/sign_up_terms_agreement.ui.test.js
Closes #637
Added a `flashMessage` option to the show method.
Showing an error flash message:
```js
lock.show({
flashMessage:{
type: 'error',
text: 'error message'
}
});
```
Showing a success error message:
```js
lock.show({
flashMessage:{
type: 'success',
text: 'success message'
}
});
```
Showing errors in redirect mode:
```js
lock.on("authorization_error", function(error) {
lock.show({
flashMessage:{
type: 'error',
text: error.error_description
}
});
});
```
> Allow to display a flash message on lock.show

- src/core/index.js
- src/quick-auth/actions.js
- test/helper/ui.js
- test/social_login.test.js
```js
Auth0Lock(cid, domain, {
auth: {
connectionScopes: {
'google-oauth': ['scope1', 'scope2'],
'facebook': ['scope1', 'scope2']
}
}
});
```
> Support connectionScopes for oauth2 connections

- src/connection/enterprise/hrd_screen.jsx
> Single AD connection without domain shows undefined in message

- src/connection/database/login_sign_up_tabs.jsx
> Fix Issues with Overlay mode + signUpLink setting on a SPA

- src/core/index.js
- src/i18n.js
- src/i18n/en.js
- test/i18n.test.js
- It will use the `en` dictionary as a default for missing keys.
- If there is any missing key, it will throw a warning in the console.
> Added default values to the dictionary and warn about missing keys

- src/connection/database/index.js
- src/core/index.js
- src/engine/classic/login.jsx
- support/index.html
- test/connection_pick.ui.test.js
- test/layout.ui.test.js
> Enterprise: force username for AD connections

- README.md
According to the Lock 9 to Lock 10 migration doc the `callbackUrl` was renamed to `redirectUrl`.
> Correcting callbackUrl to be redirectUrl

- src/i18n/ru.js
Please change the Russian translation for the signUpLabel key from "Зарегистрироваться" to "Регистрация". Semantically it's the same but "Зарегистрироваться" is longer and does not fit well into the width of container. Consider the following screenshots:
> Shorten Russian signUpLabel to fit into the widget width

- package.json
- scripts/ci.sh
- src/core/index.js
- src/core/remote_data.js
- src/core/web_api/legacy_api.js
- src/core/web_api/p2_api.js
- support/index.html
- default scope to openid for non oidc conformant
- disable sso properly
- validate reponseType with popup
- added parsehash for legacy
> Auth0js v8 - configuration validation + default scope

- package.json
- src/core/web_api.js
- src/core/web_api/legacy_api.js
- src/core/web_api/p2_api.js
Closes #791 (notify)
Also disables warnings of auth0.js in default mode
> Bring back support for get profile in default mode

- src/core.js
Looks like Lock v10.8.0 added event validation via https://github.com/auth0/lock/pull/756. However this feature emits error messages for many events that Lock makes available (e.g. those events from https://github.com/auth0/docs/pull/191). 
This bug occurs on all supported browsers and operating systems since at least the v10.8.0 release, including the latest version today.
I simply added 'signin ready' to the whitelist of valid events: https://github.com/auth0/lock/blob/master/src/core.js#L36
There are other events in https://github.com/auth0/docs/pull/191 that have the same issue but for my purposes I only need 'signin ready' fixed in order to unblock my production issue. 
When I build this branch locally I no longer see the 'Invalid event' console error.
The following code in my …
> Don't emit error when registering for event 'signin ready'

- README.md
- src/core.js
- src/core/actions.js
- src/core/index.js
When Lock redirects to the redirect url,  it puts the params after a `#` (eg: `#id_token=foo&access_token=bar`. This causes some issues with client side routers that use `#` to handle urls. An example is https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/issues/40.
This PR adds an option to prevent parsing the hash when you instantiate lock (`autoParseHash`) and adds the `resumeAuth` method to resume the authentication steps  (including all the events)
> Add resumeAuth method and autoParseHash flag

- package.json
In the previous version of auth0.js, it whitelisted oauth2 only parameters, that produced to lost some parameters needed by auth0-server to carry on session information.
> Bump auth0.js to 8.1.2

- src/core/index.js
- src/engine/classic.js
- support/index.html
> Only set prefill values when client is initialized

- src/__tests__/field/__snapshots__/mfa_code_pane.test.jsx.snap
- src/__tests__/field/mfa_code_pane.test.jsx
- src/field/mfa-code/mfa_code_pane.jsx
The complete dialog is disabled while submitting, there's no need to disable this particular input separately. 
As can be seen in `email_pane` and `username_pane`, they don't include this `disabled` property either.
Fixes issue with cordova: the first time the mfa-code input is displayed it starts in a disabled state until you click once in submit.
>  Don't disable mfa-code input

- src/engine/classic.js
> Throw an error if login, signUp and forgotPassword screens are not allowed

- css/index.styl
> Fix a box-sizing issue that happened when bootstrap was being used with lock

- package.json
Start using tilde (~) for auth0.js version to get patches automatically.
Fixes #867 by including https://github.com/auth0/auth0.js/pull/370
> Updated auth0.js to v8.3.0

- src/field/email.js
- test/regression.test.js
This fixes #884 that the Lock form can be submitted after removing the value from the email input.
> Fix #884: ability to submit form after removing the email from the input

- README.md
As stated in [this support ticket](https://support.auth0.com/tickets/20698) the sso switch does not actually influence the creation of a SSO session on the Auth0 side. This is imho not properly reflected in the docs for this switch, so I updated it.
I'm still not sure if the `sso` switch in the current state couldn't be unified with `rememberLastLogin` because, according to the ticket, both are only frontend features and the SSO data is probably not used for other cases.
> Clarify `sso` option behavior in the README

- src/connection/database/actions.js
> Don't clear email field after reset password

- src/core/actions.js
__Rationale__: Currently, when we get to the login callback, the callback url with and without the hash will be counted as two different browser history entries. This leads to the user not having the possibility to navigate back as the history entry that includes the hash will always trigger the authentication procedure again. Additionally I don't like the idea of tokens appearing in my browser history, because this way an attacker could steal them from there (although they will only be valid for a limited amount of time).
__Implementation__: Replace `window.location.hash = ''` with `window.history.replaceState(` so it will not create an additional history entry, but replace the existing one that includes the hash.
What do you think?
> Use replaceState for better browser history experience

- src/engine/classic.js
- src/sync.js
- src/utils/cdn_utils.js
> Improve error handling of sync with better errors

- src/ui/box/header.jsx
Change propType `backgorundColor` to `backgroundColor`. Little bit of shameless self-promotion here, but I caught this using [maybe-you-meant](https://github.com/nickpisacane/maybe-you-meant) while working on an app of mine. Appreciate the great work on Lock!
> fixed propType misspell in header.jsx

- css/index.styl
- src/ui/box/header.jsx
> Fix long header title and Error messages overflow

- package.json
- src/ui/box/container.jsx
- support/playground/index.html
- test/out-of-date/lock/index.js
- yarn.lock
Image url cache header comparison example:
```bash
➜  lock git:(improve-perf) curl -s -I https://cdn.auth0.com/styleguide/1.0.0/img/badge.png | grep "Cache-Control"
Cache-Control: public, max-age=300
➜  lock git:(improve-perf) curl -s -I https://cdn.auth0.com/styleguide/components/1.0.8/media/logos/img/badge.png | grep "Cache-Control"
Cache-Control: max-age=2628000,public
```
> Update badge location for better performance and bundle max-age changes

- src/__tests__/ui/box/__snapshots__/global_message.test.jsx.snap
- src/__tests__/ui/box/global_message.test.jsx
- src/ui/box/chrome.jsx
- src/ui/box/global_message.jsx
As part of https://github.com/auth0/lock/issues/878#issuecomment-286882027, successfully merged through https://github.com/auth0/lock/pull/928 you enabled html formatting in error/success messages.
However this only work only through languageDictionary strings and not when the message is called through: `lock.show({flashMessage: {...})`
This small change should fix that.
> Enabled HTML formatting for flashMessages

- src/core/actions.js
> Emit authorization_error when username/password fails (invalid_user_password)

- src/__tests__/core/web_api/helper.test.js
- src/__tests__/core/web_api/legacy_api.test.js
- src/__tests__/core/web_api/p2_api.test.js
- src/core/web_api/helper.js
- src/core/web_api/legacy_api.js
- src/core/web_api/p2_api.js
Overrides are currently not working, because auth0.js requires them to be part of `opts.overrides`, while currently they are being added on `ops` directly.
Reference: https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L48-L53
> Fixed overrides sent to auth0.js

- README.md
- src/__tests__/ui/box/global_message.test.jsx
- src/core.js
- src/core/index.js
- src/ui/box/chrome.jsx
- src/ui/box/container.jsx
- src/ui/box/global_message.jsx
- support/index.html
Messages might appear outside of users viewport. This PR fixes this by scrolling global messages into the users viewport. Hiding the users keyboard doesn't fix the problem because of the huge amount of different resolutions and display ratios.
see https://github.com/auth0/lock/issues/959
> Scroll messages in all lock dialogs into view

- README.md
- src/__tests__/field/__snapshots__/email_pane.test.jsx.snap
- src/__tests__/field/__snapshots__/username_pane.test.jsx.snap
- src/__tests__/field/email_pane.test.jsx
- src/__tests__/field/username_pane.test.jsx
- src/connection/database/actions.js
- src/core/index.js
- src/engine/classic/login.jsx
- src/field/email/email_pane.jsx
- src/field/username/username_pane.jsx
- src/ui/input/email_input.jsx
- src/ui/input/username_input.jsx
> Adding a custom connection resolver option

- src/connection/database/actions.js
- src/connection/database/index.js
Looks like the `connectionResolver` option was added in 10.19 to allow control over which connection to authenticate against during `logIn`. We've been using this feature since its release, and it's worked well so far.
We've noticed that `resetPassword` does not respect this function, and this can result in some really confusing behavior. For users whose default connection is overridden by the `connectionResolver`, they could be logging into one connection but resetting their password in another. And so their interaction with the Lock might go as follows:
* Log in for the first time in a month and don't really remember their password. They try their default. Incorrect.
* They click "Forgot your password?" and trigger a password reset email. They click on the link in the email and submit a …
> Resolve connection for reset password

- README.md
The old code suggestion would prevent users that like or need to zoom their browser content from doing so. The new suggestion presents a sensible default without locking users out of sometimes-essential assistive technology.
This also brings the README and the docs at https://auth0.com/docs/libraries/lock/v10 in sync.
> Avoid recommendations that hamper users that zoom their browser

- package.json
- yarn.lock
This upgrade includes some fixes for tenant overwrite that were included in auth0.js 8.10: https://github.com/auth0/auth0.js/tree/v8.10.0
> upgrade auth0.js

- package.json
- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/core/web_api/p2_api.js
- yarn.lock
Also removed `sso` param because there's no use for it in the OIDC flow
> Upgrading auth0-js with fixed state checking

- src/i18n/ro.js
Hey there,
The Romanian language uses polite second-person pronouns in formal settings (see https://en.wikipedia.org/wiki/Personal_pronounhttps://en.wikipedia.org/wiki/Personal_pronoun#Formality). The thing is:
- The translations were inconsistent, sometimes the formal version was used, sometimes the informal one
- The audience is different depending on the application folks are building. I'd probably go as far as to say there could probably be two versions of the translation, one for "formal" settings, and one for "informal"? You would't want to address kids/students using a very formal tone, but maybe you would for the customers of a bank, for example? 
**Either way, for now this patch does two things:**
- Fixes the formality inconsistency, the tone used now is informal, not a mix of …
> [RFC] Slightly better Romanian translations

- package.json
- yarn.lock
For full details https://auth0.com/docs/security/bulletins/cve-2017-17068.
This upgrades the dependency to the latest version of auth0-js.
> Fix security vulnerability CVE-2017-17068

- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/__tests__/core/web_api/p2_api.test.js
- src/core/web_api/p2_api.js
To be able to set plugins during embeded Lock creation. For example:
```
const lock = new Auth0Lock(clientId, domain, {
plugins: [new CustomPlugin()],
});
lock.show();
```
> `plugins` option added. Forwarded to WebAuth.

- css/index.styl
- src/__tests__/ui/box/__snapshots__/global_message.test.jsx.snap
- src/__tests__/ui/box/global_message.test.jsx
- src/core.js
- src/core/actions.js
- src/core/index.js
- src/ui/box/chrome.jsx
- src/ui/box/container.jsx
- src/ui/box/global_message.jsx
- test/helper/ui.js
- test/show_with_flash_message.test.js
As discussed in #1220, we want to add a new `flashMessage` type `info` in order to show messages that are neither an error nor a success message.
> Add new flash message type `info`

- README.md
There was a couple of links using http protocol which should be replaced with https. Since all endpoints accept https it shouldn't break anything (I did test that).
> Replace http links with https protocol.

- README.md
- src/index.js
- src/lock.js
> Fixing Auth0LockPasswordless export

- src/core/remote_data.js
the quick auth screen is only shown when rememberLastLogin is true, so there's no need to cal getSSOData if we're not showing that screen.
fix #1238
> Only call getSSOData when rememberLastLogin is true

- src/core.js
- src/engine/classic.js
- src/engine/passwordless.js
- src/ui/box/chrome.jsx
- support/index.html
fix https://github.com/auth0/lock/issues/1263
fix https://github.com/auth0/lock/issues/1264
> Fix Lock Passwordless feature parity (events and quick auth screen)

- .npmignore
Your `.babelrc` file is published to npm. This causes i.e that if I want to transpile my project along with dependencies, I am dependent on your babel configuration (plugins, presets, etc).
Could you please add `.babelrc` file to `.npmignore`?
> Added .babelrc to .npmignore

- src/__tests__/core/web_api/p2_api.test.js
- src/core/web_api/p2_api.js
The correct way of sending the `state` parameter in the authentication request is
```js
var options = {
auth: {
params: { state: 'foobar' }
}
}
```
But, because of the bug I just fixed, this state, although being sent in the auth requests, wasn't being sent in the parseHash method, which caused the '`state` doesn't match' error.
This gets the correct state without breaking anyone.
With this code, both version will work for parsing the hash with a specific state:
```js
var options = {
auth: {
params: { state: 'foobar' }
}
}
```
```js
var options = {
auth: {
state: 'foobar'
}
}
```
> Fix inconsistent state assignment

- README.md
The docks describe options as:
```var options = {
auth: {
params: {scope: 'openid email user_metadata app_metadata picture'},
}
};``` 
(https://auth0.com/docs/libraries/lock/v11/sending-authentication-parameters)
But checksession seems to expect a params object like this:
```{scope: 'openid email user_metadata app_metadata picture'}```
> Clarify checksession accepts params and not options

- src/ui/box/chrome.jsx
- test/helper/ui.js
- test/layout.ui.test.js
Discussion about the issue: https://spectrum.chat/?t=90bc0f1b-54fc-40f4-b718-353e80b47cdc
TLDR: Password managers use `form.submit()` to submit the form. This, according to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit), prevents the `onsubmit` event from being emitted, which prevents react to handle the event.
> When invoking this method directly, no submit event is raised (in particular, the form's onsubmit event handler is not run),  and constraint validation is not triggered either.
The fix is also in the docs: 
> If a form control (such as a submit button) has a name or id of submit it will mask the form's submit method.
So, all we have to do is to add `name="submit"` to our submit button. In our specific case, I also had to change the behavior to …
> Fix password managers submitting the form incorrectly

- css/index.styl
Currently, if a user clicks directly on the arrow icon in a select field, nothing will happen.
This PR applies `pointer-events: none` to the arrow icon. As a result, clicking on the icon will now open the select menu.
> Allow select field arrow to be clicked

- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/core/web_api/helper.js
As far as I can tell, Lock's `popupOptions` config option is removed by the `normalizeAuthParams` helper and never gets passed to auth0.WebAuth (in either the p2 or legacy apis) where it is used to control the `window.open` settings. Therefore the current `popupOptions` setting listed in the documentation is misleading (it doesn't work)...
> Ensure popupOptions gets passed to auth0.WebAuth

- src/__tests__/core/index.test.js
- src/__tests__/testUtils.js
- src/__tests__/utils/url_utils.test.js
- src/core/index.js
- src/utils/url_utils.js
> Fix IE default redirect url

- src/__tests__/core/remote_data.test.js
- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/__tests__/core/web_api/p2_api.test.js
- src/core/remote_data.js
- src/core/sso/data.js
- src/core/web_api/p2_api.js
- test/helper/ui.js
We're not sending the `AD` flag to auth0.js when we call getSSOData. This is fine for embedded since we ignore this flag. But for hosted pages, which use the /ssodata endpoint, this flag is required in order to return information about AD connections.
> Sending AD information when calling getssodata

- src/__tests__/connection/database/index.test.js
- src/connection/database/index.js
Today when you have an enterprise connection configured and you type in an email address that matches the domain of this connection (eg: john@contoso.com => contoso.com), the login/signup/password reset pages will take that into account.
- Login => will change to SSO mode
- Signup => will change to SSO mode
- Password Reset => will prevent you from changing your password with a message saying you need to contact your administrator
While this works fine for database connections, there is an issue when the database connection requires a username. With usernames required, the `databaseUsernameValue` method will only look at the username field. While this works for the login page, it does not for signup and password reset (because there you enter your email address ... in the email field). …
> Fallback to email if the username field is empty

- src/__tests__/connection/database/index.test.js
- src/__tests__/connection/database/reset_password.test.jsx
- src/__tests__/engine/classic/sign_up_screen.test.jsx
- src/connection/database/index.js
- src/connection/database/reset_password.jsx
- src/engine/classic.js
- src/engine/classic/sign_up_screen.jsx
fix https://github.com/auth0/lock/issues/1409
> Fix SSO screen not showing in some cases

- css/index.styl
- src/__tests__/field/__snapshots__/login_pane.test.jsx.snap
- src/__tests__/field/__snapshots__/password_pane.test.jsx.snap
- src/__tests__/field/password_pane.test.jsx
- src/connection/database/login_pane.jsx
- src/field/password/password_pane.jsx
- test/helper/ui.js
- test/layout.ui.test.js
Fix https://github.com/auth0/lock/issues/1397
The issue happened because Lock was REMOVING the password input from the DOM. The fix was to let the input in the DOM, but add a css class that hides the input.
Before:
After:
> In SSO mode, hide the password input instead of removing it from the DOM

- src/core/index.js
- test/tenantinfo.test.js
ZD Num: 43661
This generates the right configuration URL when a `baseConfigurationUrl` is set and Tenant Info is being used.
Fixes #1417
> Fix Configuration URL when using __tenantInfo and a baseConfigurationURL

- src/__tests__/core/web_api/__snapshots__/helper.test.js.snap
- src/__tests__/core/web_api/helper.test.js
- src/core/web_api/helper.js
- src/core/web_api/p2_api.js
Fix issue with incorrect error message mapping in case of session timeout. The returned payload is:
```
{
"statusCode": 403,
"description": "Invalid state",
"name": "AnomalyDetected",
"code": "access_denied"
}
```
Currently this kind of error is mapped to `invalid_user_password` which causes UX regression to one of our customers. 
@luisrudge suggested we could fix this issue by preventing the mapping in Hosted Login Pages environment.
> prevent access_denied to invalid_user_password error or code mapping if in HLP env

- src/engine/classic.js
Imported isADEnabled since it's used but not imported.
> Imported isADEnabled for latter use

- src/connection/enterprise.js
Lock was trying to log an object that doesn't exist
> Fixed warning

- src/__tests__/engine/classic.test.js
- src/engine/classic.js
fix https://github.com/auth0/lock/issues/1434
> Fix crash when showing lock for the second time with custom select input

- src/__tests__/core/web_api/p2_api.test.js
- src/core/web_api/p2_api.js
Ensure the supplied login_hint is used over any default auth/params
Fixes: #1426
> Fixed login_hint in some enterprise authorize call scenarios

- README.md
- src/__tests__/connection/database/index.test.js
- src/__tests__/engine/classic/__snapshots__/sign_up_pane.test.jsx.snap
- src/__tests__/field/__snapshots__/custom_input.test.jsx.snap
- src/__tests__/field/custom_input.test.jsx
- src/connection/database/index.js
- src/engine/classic/sign_up_pane.jsx
- src/field/custom_input.jsx
fix #1324 
adds a new type (hidden) of custom signup fields:
To specify a hidden field use: `type: "hidden"`. Both the `value` and `name` properties are required.
```js
var options = {
additionalSignUpFields: [{
type: "hidden",
name: "signup_code",
value: "foobar123"
}]
}
```
> Add a new type of additionalSignUpField: hidden

- src/i18n/ja.js
Hideya Furuta requested this change through a support ticket.
He said: Please modify the letters for 2nd line: 3 が含まれています: 4 to 下記の 4 つのうち 3 つ以上含んでください.
Current configuration 3 が含まれている: 4 is not match for Japanese sentence, and customers claimed they couldn't understand the meanings.
> Update ja.js containsAtLeast text

- css/index.styl
- src/ui/box/button.jsx
Fixes regression in v11.9.0
In 11.9.0, for accessibility, some 'span' tags were switched to 'button'.
However hitting the enter key triggers the onClick on buttons. (not sure where this is in the code, but it might be worth changing)
So switching back to 'span' for now.
> Use span for icon buttons

- src/__tests__/connection/database/reset_password.test.jsx
- src/connection/database/reset_password.jsx
**Description**
When `avatar: null` is specified in the the Lock configuration options, reset password will not display the enterprise error when an enterprise domain is detected. 
**References**
ZD #48775
**Notes**
This is a hot patch, I feel a more complete solution that addresses the root cause that is rapid duplicate calls to the [isSubmitDisabled](https://github.com/auth0/lock/blob/fixed-enterprise-null-avatar/src/connection/database/reset_password.jsx#L43) method should be looked at. Although this requires more in depth platform knowledge.
> [Sustainment] Fixed Reset Password Avatar/Enterprise Issue

- css/index.styl
- src/ui/input/input_wrap.jsx
The "hrd.not_matching_email" `invalidHint` is coming into `InputWrap` as HTML, presumably as intended, but the `InputWrap` component is not expecting that. This causes a couple things:
- Locally, it throws an exception, because the PropType of `string` is violated occasionally.
- Because the component is otherwise unaware that HTML might be coming in, the css was written with a generic selector (`span`) to apply box/border styling. This causes double padding if HTML comes in pre-packaged as a span.
This PR gives that component some flexibility to deal with the possibility that fully formed html might be coming in.
It looks like most, if not all, of the `<input>_pane` components could be updated to always pass html to be consistent. `CustomInput` would need some love, too. 💭 
(Before) …
> Handle HTML in the `invalidHint` better

- css/index.styl
- src/__tests__/engine/classic/__snapshots__/login.test.jsx.snap
- src/__tests__/engine/classic/__snapshots__/sign_up_screen.test.jsx.snap
- src/engine/classic/login.jsx
- src/engine/classic/sign_up_screen.jsx
- src/engine/passwordless/social_or_email_login_screen.jsx
- src/engine/passwordless/social_or_phone_number_login_screen.jsx
When we did https://github.com/auth0/lock/pull/1539, I had to create another div to wrap the internal content. It was copy/paster in every "screen" component, but I forgot in some of them. Instead of continue the copy/paste, I added the padding to the screen's wrapper component. This will have the same effect and it works with all screens (current and new) OOTB.
https://github.com/auth0/lock/pull/1539
> Fix padding in all screens

- css/index.styl
Minor cosmetic changes.  When logging in with Firefox (tested on latest, 63.0.1), the error tooltips wrap and overlap.  This adds `white-space: nowrap` to the outer lock-cred-pane to prevent the error tooltips from wrapping.
SF Support Case
> updated lock-cred-pane

- src/__tests__/connection/database/__snapshots__/password_reset_confirmation.test.jsx.snap
- src/__tests__/connection/database/__snapshots__/signed_up_confirmation.test.jsx.snap
- src/__tests__/connection/database/password_reset_confirmation.test.jsx
- src/__tests__/connection/database/signed_up_confirmation.test.jsx
- src/__tests__/connection/passwordless/__snapshots__/email_sent_confirmation.test.jsx.snap
- src/__tests__/connection/passwordless/email_sent_confirmation.test.jsx
- src/__tests__/core/__snapshots__/signed_in_confirmation.test.jsx.snap
- src/__tests__/core/signed_in_confirmation.test.jsx
- src/__tests__/ui/box/__snapshots__/confirmation_pane.test.jsx.snap
- src/__tests__/ui/box/confirmation_pane.test.jsx
- src/connection/database/password_reset_confirmation.jsx
- src/connection/database/signed_up_confirmation.jsx
- src/connection/passwordless/email_sent_confirmation.jsx
- src/core/signed_in_confirmation.jsx
- src/ui/box/confirmation_pane.jsx
fix https://github.com/auth0/lock/issues/1556
Passing the lock instance as props so the confirmation pane (only shown when redirect:false) doesn't throw an error.
https://github.com/auth0/lock/issues/1556
> Fix `lock is undefined` error in non-redirect scenarios

- css/index.styl
fix #1591 
also revers and fixes #1566
- Set position to `fixed` to make sure it's always centered in the screen
- Set overflow-x to `auto` to make sure lock always scrolls when the signup form is bigger than the viewport
#1591 
#1566
> Fix lock center position with scroll across browsers

- src/i18n/ja.js
Japanese format wrong.
> passwordStrength. containsAtLeast
- [Old] '下記の%dつのうち%dつ以上含んでください:' means by english, "Please include at least 4 out of 3".
↓
- [New] '%dつ以上の条件を満たす必要があります。（条件は以下の％dつ）'
> welcome
- [Old] '%sへようこそ！' means by english, "Come on [UserName]". OMG!!
↓
- [New] 'ようこそ%sさん'
> Japanese format wrong with containsAtLeast and welcome

- src/i18n/ja.js
Sorry, I mistaked japanese format : ”%” is double-byte character, so to change to single-byte character.
> ”%” is double-byte character

- src/i18n/de.js
'Sign up' in German is 'Registrieren', not 'Anmelden'.
> Changes german translation of 'sign up' from 'Anmelden' to 'Registrieren;

- css/index.styl
Fix an UI issue when using a big string in the 'accept terms' area.
> Fix layout when using big string for terms

- README.md
- src/__tests__/__snapshots__/auth_button.test.jsx.snap
- src/__tests__/auth_button.test.jsx
- src/__tests__/engine/classic/__snapshots__/login.test.jsx.snap
- src/__tests__/engine/classic/__snapshots__/sign_up_screen.test.jsx.snap
- src/__tests__/engine/classic/login.test.jsx
- src/__tests__/engine/classic/sign_up_screen.test.jsx
- src/__tests__/field/__snapshots__/social_buttons_pane.test.jsx.snap
- src/__tests__/field/social_buttons_pane.test.jsx
- src/connection/social/index.js
- src/core/index.js
- src/core/sso/last_login_screen.jsx
- src/engine/classic.js
- src/engine/classic/login.jsx
- src/engine/classic/sign_up_screen.jsx
- src/engine/passwordless.js
- src/engine/passwordless/social_or_email_login_screen.jsx
- src/engine/passwordless/social_or_phone_number_login_screen.jsx
- src/field/social/social_buttons_pane.jsx
- src/ui/button/auth_button.jsx
- support/design/index.html
- support/design/modal.html
- support/index.html
- support/playground/index.html
- support/playground/index.js
Removes the `socialButtonStyle` option. This will remove the option to use `small` icons.
> Remove socialButtonStyle option to use small icons

- src/__tests__/field/password.test.js
- src/field/password.js
fix https://github.com/auth0/lock/issues/1282
Always set the password to invalid when there's no password
> Prevent form submit when password is empty

- src/store/index.js
fix #907, https://github.com/auth0/lock/issues/1090, https://github.com/auth0/lock/pull/1091
This is a copy of https://github.com/auth0/lock/pull/1091, but I couldn't rebase because the original branch was removed.
This fixes a case where lock couldn't be destroyed `lock.destroy()`.
> Fix destroying lock instance

- src/__tests__/core/__snapshots__/tenant.test.js.snap
- src/__tests__/core/tenant.test.js
- src/core/tenant/index.js
fix https://github.com/auth0/lock/issues/1612
We changed password policies to objects a while ago (policies here https://github.com/auth0/auth0-password-policies), but the tenant connections didn't get the update.
> Fix password policy when using tenant connections

- package.json
- yarn.lock
fix https://github.com/auth0/lock/issues/1703
For some reason, we were using the github version of the lib and this fails in some cases (when the machine doesn't have git installed etc). This PR changes the dependency to load from npm.
> Fix CDN dependency

- css/index.styl
Fixes #1610
Currently, when all social sign-up buttons are disabled (for example due to not checking agreement to terms), Google's social login button lights up when hovering/focusing on it.
This PR adds the `not(disabled)` to CSS to avoid that.
To reproduce the bug:
1. Enable social logins with Google.
2. Set `mustAcceptTerms` to true.
3. On sign-up page, hover over Google and expect button to be disabled.
Tested in Chrome browser by applying fix directly in dev tools.
> Fixes styling in Google Login when button is disabled

- src/core/index.js
Make sure devs copying/pasting code from auth0.js get a warning because both options have very similar names
> Warn when `auth.redirectUri` is sent as an option

- src/__tests__/field/email.test.js
- src/field/email.js
- src/ui/input/email_input.jsx
To better handle unicode values in the domain part, we need to relax the email validation. After some internal discussions, I decided that it's easier to let the server decide if the email is valid or not. This PR only validates that the email:
- is a string
- has a `@`
- has a `.`
- doesn't have a ` ` (white space)
I think this is all that is right amount of balance between the user experience and actual email validation
ESD-2239
> Relaxing the email validation

- css/index.styl
- src/__tests__/__snapshots__/auth_button.test.jsx.snap
- src/__tests__/engine/classic/__snapshots__/sign_up_screen.test.jsx.snap
- src/__tests__/field/__snapshots__/social_buttons_pane.test.jsx.snap
- src/__tests__/field/social_buttons_pane.test.jsx
- src/connection/database/actions.js
- src/engine/classic/sign_up_screen.jsx
- src/engine/passwordless/social_or_email_login_screen.jsx
- src/engine/passwordless/social_or_phone_number_login_screen.jsx
- src/field/social/social_buttons_pane.jsx
- src/i18n/en.js
- src/ui/button/auth_button.jsx
- support/index.html
Today, if social providers are enabled, the buttons are greyed out until the user accepts the TOS.The TOS checkbox is presented at the bottom, so it is hardly visible, leaving the end-user wondering if the social login buttons are broken or not working for another reason.
This PR adds an error box when the social button is clicked but the terms haven't been accepted:
The final copy can be changed, that's why I haven't translated all the files yet (will have to do before merging).
https://auth0team.atlassian.net/browse/SDK-751
> Fix social button interactions when terms have not been accepted

- src/__tests__/core/index.test.js
- src/core/index.js
This PRs fixes an error mapping (from `password_expired` to `password_change_required`) in order to provide a better error message for end users.
Fix https://github.com/auth0/lock/issues/1719
> Map password_expired to password_change_required

- src/i18n/fi.js
This PR adds missing `error.signUp.social_signup_needs_terms_acception` property that was added in https://github.com/auth0/lock/pull/1733 to the finnish localization
This this blame shows the added line: https://github.com/auth0/lock/blame/1766f2259b81b345d11f5b6f371d4132c85f63a7/src/i18n/en.js#L47
Fixed by adding it to my own languageDictionary
> fix: Add missing property for finnish translation

- css/index.styl
Reset the `display` property on `.auth0-lock-form` when on iPhone. Also reset padding on the content element, as `initial` removes this when applied.
This should fix an issue where the form isn't displayed properly when first displayed on the screen, as verified using a sample repo kindly provided by @ajmueller (https://github.com/auth0/lock/issues/1588#issuecomment-537199399).
Fixes #1588 
* #1588
* https://github.com/auth0/lock/issues/1588#issuecomment-537199399
Tested using the iPhone simulator running the sample repo provided for this issue.
> Reset .auth0-lock-form display to 'initial' for iPhone

- README.md
- src/connection/enterprise/actions.js
This extends the existing event emitter pattern with a new event, called `sso login` (casing & spacing follows the existing `federated login` event name for social).
Our current use case for this is to make some adjustments (which have to be pre-login) based on our enterprise clients with their own IdPs logging in by doing our own lookup of the client's configuration.
This will help with a support ticket on my company's account: https://support.auth0.com/tickets/00439926
The existing `npm run test:cli` passes. I do not see any unit test cases currently existing for event emitters such as `federated login` so it doesn't appear to be a pattern now. I don't have access to Saucelabs to run the default `npm test`.
> Add a Lock event 'sso login'

- src/utils/url_utils.js
Can you approve this change to handle WebExtensions, please? The auth0-lock and auth0-js projects are affected by this change. I used auth0-chrome which is supposed to work for the extensions, but this library is not adapted and poses problems of ergonomics.
Thanks in advance.
> Bugfix for WebExtension

- css/index.styl
Ensures that the `overflow-x: auto` style is only applied to mobile views (< 480px). Otherwise, it breaks the password strength popup on desktop views, as the wrapper can hide the top portion of it.
However, the overflow style is needed to fix the "submit" button on mobile views.
**Before**
**After**
Fixes #1756 
Fixes #1705 
> Applied overflow style only on mobile views

- css/index.styl
- src/__tests__/__snapshots__/auth_button.test.jsx.snap
- src/__tests__/auth_button.test.jsx
- src/ui/button/auth_button.jsx
Lock social buttons now render as links instead of buttons. This is to fix an issue with LastPass not attaching its buttons to the input boxes on load.
I believe this is a security issue with LastPass (see [security considerations](https://hiddedevries.nl/en/blog/2018-01-13-making-password-managers-play-ball-with-your-login-form) on this doc). It won't initialize the extension on the form fields until some user interaction has happened, because there are button tags within the form (the social buttons). If a site hosting Lock was vulnerable to XSS attacks, they could potentially post login information to a malicious location if LastPass did actually pre-fill those form fields on page load.
Changing these buttons to links (without affecting the styles, other than providing an affordance …
> [SDK-1191] Lock social buttons now render as links instead of buttons

- package.json
- yarn.lock
This is a bump of Auth0.js to 9.12.0 to support better OIDC compliance when validating ID tokens.
> [SDK-980] Bumped auth0.js to 9.12.0

- package.json
- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/__tests__/core/web_api/p2_api.test.js
- src/core/web_api/p2_api.js
- yarn.lock
This PR bumps Auth0.js to 9.12.1 to take advantage of a new default leeway. It also changes the default leeway specified by Lock to align with Auth0.js to 60 seconds.
Aligns with this change: https://github.com/auth0/auth0.js/pull/1062
Unit test coverage added. It's not immediately obvious from the way the diff has worked out, but the change is verified in the form of an additional snapshot. Existing tests used a leeway of 60 seconds; these were changed to 30 seconds to distinguish these tests from the new test that sends the default of 60.
> Set the default token validation leeway to 60 sec

- src/connection/database/actions.js
- src/field/captcha/captcha_pane.jsx
- test/captcha.test.js
Do not post the login form when captcha is **required** but is **empty**.
- Jira CAUTH-277
> [CAUTH-277] prevent posting when captcha is required and empty

- package.json
- yarn.lock
Bumped Auth0.js to gain access to the [change that removes the issued-at claim check](https://github.com/auth0/idtoken-verifier/releases/tag/v2.0.1).
> Bumped Auth0.js to 9.12.2

- src/__tests__/quick-auth/__snapshots__/actions.test.js.snap
- src/__tests__/quick-auth/actions.test.js
- src/__tests__/ui/box/__snapshots__/container.test.jsx.snap
- src/__tests__/ui/box/container.test.jsx
- src/core.js
- src/core/actions.js
- src/core/index.js
- src/quick-auth/actions.js
- src/ui/box/container.jsx
This PR adds the ability to prevent the "loading" overlay from being shown when a user clicks on a social connection to log in. Additionally, it uses this feature to prevent the overlay from being shown when the "Sign In With Apple" connection was used. This is to work around an issue where, if the user elects to sign in using their Apple account and the native "Sign In With Apple" UI is shown and the user cancels it, they would otherwise get stuck because of this overlay.
To test, add the "Sign In With Apple" social connection to your Auth0 app, invoke Lock, attempt to sign in on an iOS device and then cancel. The user should be able to continue on and select a different connection.
Additional unit test coverage has been added to cater for the new functionality, including implementing a …
> Prevent loading overlay from showing when using Sign In With Apple

- src/__tests__/connection/passwordless/__snapshots__/passwordless.actions.test.js.snap
- src/__tests__/connection/passwordless/passwordless.actions.test.js
- src/connection/passwordless/actions.js
- yarn.lock
With this PR, the `authorization_error` event is now emitted when an error occurs while submitting a code in the passwordless flow.
Originated from an internal service desk ticket.1
> Emit authorization_error event on passwordless error

- css/_mixins&keyframes.styl
- css/index.styl
- src/core.js
- src/lock.js
This PR resolves an issue on mobile where the login button was being cut off towards the bottom of the screen. This PR implements the [technique on CSS Tricks](https://css-tricks.com/the-trick-to-viewport-units-on-mobile/) to dynamically calculate the screen height and apply that to a custom variable on `:root` where it can be picked up by the CSS. It uses `100vh` as a fallback for those browsers that do not support custom variables.
See screenshots in comments.
Fixes #1706 
Partial fix for #1783 
This has been tested manually on:
* Samsung Galaxy S6 (Chrome, Firefox)
* Samsung Galaxy S9 (Chrome, Firefox)
* Samsung Galaxy Note 8 (Chrome)
* Pixel 1 (Chrome)
* OnePlus 6T
* Chrome Desktop
* Firefox Desktop
* IE11
> Fix for login button being cut off on some mobile devices

- src/i18n/da.js
- src/i18n/de.js
- src/i18n/it.js
- src/i18n/nb.js
- src/i18n/nl.js
- src/i18n/nn.js
- src/i18n/no.js
- src/i18n/sv.js
This PR adds missing translations for:
* Dutch
* Italian
* Norweigen
* German
* Swedish
* Danish
All of these except for one German translation has been provided by Google Translate.
> [SDK-1300] Added missing translation keys for 6 EU languages

- css/index.styl
This PR:
* Removes `text-center` on the social button text
* Adds left/right padding
This was missing from the previous update to these buttons.
*Preview*
Tested manually in the browser.
> [SDK-1361] Fix missing padding on social buttons

- css/social_icons.styl
This is a design change for compliance with Apple's guidelines. While they don't specifically call out that the button has to be full black, there are concerns that something like this might cause an app to fail. This change is precautionary.
> Change Sign in with Apple button background to full black

- css/index.styl
This makes sure the appearance value is set correctly when Bootstrap is included on the Lock template, which sets `appearance: button`. This breaks the UI in Safari, which renders the buttons without a background color.
**Before**
**After**
This originated from an internal service desk ticket.
This was tested manually by including the Bootstrap CSS on the playground template.
> [SDK-1389] Applied appearance styles for Bootstrap in Safari

- Gruntfile.js
- package.json
- yarn.lock
Use [mkcert](https://github.com/FiloSottile/mkcert) when available for `yarn dev` to generate a certificate that is trusted locally. This allows me to reference the version of lock running locally anywhere to test.
If mkcert is not installed then it will fallback to using a self-signed certificate without authority as it used to do before this change.
I've been using this change for all my other PRs. This only affects the development experience
* [] This change adds unit test coverage
* [] This change adds integration test coverage
* [] This change has been tested on the latest version of the …
> use mkcert if available for dev

- src/connection/database/actions.js
- src/core/index.js
- src/i18n/en.js
- src/i18n/es.js
Prevent the autologin of the user if captcha is required for the transaction.
https://auth0team.atlassian.net/browse/CAUTH-373
> [CAUTH-373] do not autologin the user if captcha is required

- src/i18n/az.js
add Azerbaijan language translations
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete …
> add Azerbaijan language

- src/i18n/ja.js
When I set the 'mustAcceptTerms' option was True, I noticed that the message when I signed up without agreeing to the terms of service was not translated.
- I was add translate string to 'social_signup_needs_terms_acception' key.
> add translate 'social_signup_needs_terms_acception' for japanese

- css/index.styl
- src/__tests__/ui/box/__snapshots__/chrome.test.jsx.snap
- src/__tests__/ui/box/chrome.test.jsx
- src/ui/box/chrome.jsx
- src/ui/box/header.jsx
* Re-enables scrollbars
* Fixes a regression where the password strength popup was being clipped by the header
* Fixes an issue where using Lock on a device with a small height would cause the content to spill out of its container
Fixes #1832 
> [SDK-1413] Re-added scrollbars and fixed password strength popup clip issue

- src/__tests__/field/__snapshots__/phone_number_pane.test.jsx.snap
- src/engine/passwordless/social_or_phone_number_login_screen.jsx
- src/field/phone-number/phone_number_pane.jsx
- src/ui/input/phone_number_input.jsx
This PR should fix the issue described in issue #1836, by adding an invalidHint property the PhoneNumberInput component.
The invalidHint string is taken from phoneNumberInputInvalidHint which is optional (if not provided then this feature takes no effect) and can be provided in the languageDictionary.
for example:
new Auth0LockPasswordless(clientId, domain, { languageDictionary: { phoneNumberInputInvalidHint:  "invalid phone number. only numbers are allowed" } });
Note: the phoneNumberInputInvalidHint can also be added to i18n files to make this behaviour default for the PhoneNumberInput.
https://github.com/auth0/lock/issues/1836
Please describe how this can be …
> Add invalidHint to phoneNumberInput (fix issue #1836)

- package.json
- yarn.lock
This PR bumps [auth0-js](https://github.com/auth0/auth0.js) to version 9.13.1.
[Changelog](https://github.com/auth0/auth0.js/compare/v9.12.2...v9.13.1)
Tested manually.
> Bumped auth0-js to 9.13.1

- src/__tests__/connection/passwordless/__snapshots__/passwordless.actions.test.js.snap
- src/__tests__/connection/passwordless/passwordless.actions.test.js
- src/connection/passwordless/actions.js
In the. passwordless sms authentication when there is an error in the sendSms method there is currently no event emitted which the client can listen on and react upon (for example - In our case we would like to report this to our analytics and get a better understanding of users drop in our login funnel).
The fix is in the connection/passwordless/actions.js class to emit AuthorizationErrorEvent.
Passwordless.actions test is updated to check that AuthorizationError event is emitted.
> Fix send sms error event

- css/index.styl
- src/__tests__/testUtils.js
- src/__tests__/ui/box/__snapshots__/chrome.test.jsx.snap
- src/__tests__/ui/box/__snapshots__/header.test.jsx.snap
- src/__tests__/ui/box/chrome.test.jsx
- src/__tests__/ui/box/header.test.jsx
- src/ui/box/chrome.jsx
- src/ui/box/header.jsx
This PR changes the way the header height is calculated. Previously it used to get the height once on component mount, but this proved to be problematic when the title was updated after the component was rendered and a large title caused the header height to change.
Now, the height is calculated when the `Header` component is rendered, and the height is set as a CSS variable on the document root. This should also be more performant as the old state change would cause the component to re-render.
The downside is that this is difficult to test. However, basic smoke tests for `Header` were missing, which have now been added.
**Preview**
Raised internally through an ESD ticket.
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this …
> Fix header height calculation for large titles

- src/__tests__/ui/box/__snapshots__/chrome.test.jsx.snap
- src/__tests__/ui/box/chrome.test.jsx
- src/ui/box/chrome.jsx
- src/ui/box/container.jsx
- src/ui/box/multisize_slide.js
Make sure `headerHeight` is set whenever the component mounts. So that when the Lock dialog is close and reopened, its header height gets calculated again.
Also, had to handle a couple of lint errors to pass the pre-commit hook
Fixes #1870 
Close and reopen the Lock modal, confirm that the header does not obscure the form on the second opening.
Also tested in IE11
> Header height not updated when Lock dialog is closed and reopened

- css/index.styl
The header is further down in the DOM than the close button and they have matching z-index values so the header is overlaying the close button
https://github.com/auth0/lock/blob/master/css/index.styl#L178
https://github.com/auth0/lock/blob/master/css/index.styl#L204
close button z-index should be > header z-index
fixes #1863 
Also tested in IE11
> z-index needs to be less than the close button to avoid hiding it

- src/__tests__/core/__snapshots__/web_api.test.js.snap
- src/__tests__/core/web_api.test.js
- src/core/web_api.js
This PR forces popup mode + sso mode for Electron and Cordova apps only when not on the hosted login page. This means that Electron apps where the login page is opened inside the app would not try and do a cross-origin authentication request when using the hosted ULP.
Raised by internal ESD.
Tested and verified through manual testing with a customer using an Electron app.
> Add !hostedLoginPage condition to redirect check

- src/passwordless.js
Determines the window height using JavaScript and applies height to document root when using the Passwordless UI. This takes into account any window chrome provided by mobile devices.
This is a patch that was already applied to the primary Lock UI, but not passwordless.
**Before**
**After**
Fixes #1826 
Tested manually using Browserstack + local iOS 11 Pro Simulator.
> [SDK-1556] Apply window height style to root document for Passwordless UI

- css/index.styl
- src/__tests__/ui/input/__snapshots__/input_wrap.test.jsx.snap
- src/__tests__/ui/input/password_input.test.jsx
- src/ui/input/input_wrap.jsx
- src/ui/input/password_input.jsx
Show the "Can't be blank" message under the password field when you try and submit a blank password.
fixes #1721 
> Show the "Can't be blank" message under the password input

- src/__tests__/i18n.test.js
- src/i18n.js
- test/captcha.test.js
This change allows for ‘en’ overrides.  Adds testing support to verify that the defaultDictionary is loaded, and is allowed to be overridden.
ESD-6306
Had to reorganize the captcha tests because of some race conditions that were happening intermittently
> Allows i18n en lang override

- src/__tests__/field/captcha.test.jsx
- src/__tests__/field/captcha/__snapshots__/recaptchav2.test.jsx.snap
- src/__tests__/field/captcha/recaptchav2.test.jsx
- src/field/captcha.js
- src/field/captcha/captcha_pane.jsx
- src/field/captcha/recaptchav2.js
- src/utils/createRef.js
I've refactored our ReCaptcha component in a more react-ish class. I've tested this in deep and now it seems to work as we expect.
This should be released as a **patch** because we are not changing any existing API nor adding a new ones.
I am also attaching in this PR a couple of images showing the wrong behavior.
**As you can see after getting the error the recaptcha can't be re-checked, and the form can't be submitted.**
https://auth0team.atlassian.net/browse/CAUTH-500
> [CAUTH-500] Reload recaptcha after wrong username or password

- .circleci/config.yml
- package.json
- yarn.lock
This PR bumps auth0-js to 9.13.3.
> Bump auth0-js to 9.13.3

- src/__tests__/ui/box/__snapshots__/container.test.jsx.snap
- src/ui/box/container.jsx
This change removes the HTML5 `novalidate` attribute, preventing the browser
from performing its own native validation and allowing Lock to do its
validation instead.
The native validation prevented users from submitting email addresses such as
"téstiñg.üsêr@example.com", which is a valid value on the Auth0 server side.
Raised through internal service desk ticket.
Tested manually. Cannot test through integration testing as the client-side
native validation does not kick in.
> [SDK-1756] Remove HTML5 novalidate attribute from Lock form

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Changed**
- [SDK-1756] Add HTML5 novalidate attribute to Lock form to remove native browser validation [\#1890](https://github.com/auth0/lock/pull/1890) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Bump auth0-js to 9.13.3 [\#1889](https://github.com/auth0/lock/pull/1889) ([stevehobbsdev](https://github.com/stevehobbsdev))
[SDK-1756]: https://auth0team.atlassian.net/browse/SDK-1756
> Release 11.24.4

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Added**
- [SDK-1710] Allow Lock to use connection display name field from client configuration file [\#1896](https://github.com/auth0/lock/pull/1896) ([stevehobbsdev](https://github.com/stevehobbsdev))
[SDK-1710]: https://auth0team.atlassian.net/browse/SDK-1710
> Release v11.25.0

- src/__tests__/connection/enterprise/__snapshots__/quick_auth_screen.test.jsx.snap
- src/__tests__/connection/enterprise/quick_auth_screen.test.jsx
- src/connection/enterprise/quick_auth_screen.jsx
There is a bug in the current Lock release that causes Lock to ignore the
connection display name if there are no IdP Domains configured for the
connection, even if `preferConnectionDisplayName` is `true` - this PR fixes
that so that the connection display name is used despite there being no domains
configured.
Raised through internal service desk ticket.
> [SDK-1809] Connection display name is used even when no IdP domains are available

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Fixed**
- [SDK-1809] Connection display name is used even when no IdP domains are available [\#1898](https://github.com/auth0/lock/pull/1898) ([stevehobbsdev](https://github.com/stevehobbsdev))
[SDK-1809]: https://auth0team.atlassian.net/browse/SDK-1809
> Release v11.25.1

- README.md
- src/__tests__/connection/enterprise/actions.test.js
- src/connection/enterprise/actions.js
This PR enables the capability for the `connectionScopes` options to be passed through to enterprise connections, as well as OAuth/social connections.
They are sent through a property named `connection_scope` upon authentication time.
Raised through an internal ESD.
> [SDK-1813] Send connection scope config to enterprise connections

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Fixed**
- Fallback to default language dictionary when the language file cannot be loaded [\#1912](https://github.com/auth0/lock/pull/1912) ([davidpatrick](https://github.com/davidpatrick))
- [SDK-1813] Send connection scope config to enterprise connections [\#1910](https://github.com/auth0/lock/pull/1910) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Security**
- [Security] Bump elliptic from 6.4.1 to 6.5.3 [\#1909](https://github.com/auth0/lock/pull/1909) ([dependabot-preview[bot]](https://github.com/apps/dependabot-preview))
[SDK-1813]: https://auth0team.atlassian.net/browse/SDK-1813
> Release v11.26.2

- css/index.styl
This PR removes some slight top padding from the top of the form wrapper, which
has an effect on any error message panels that are being shown.
The removal of the padding doesn't affect the UI too badly so I've decided to
just remove it.
**Without error**
**With error**
Fixes #1933
> Remove top padding from wrapper element

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Fixed**
- Remove top padding from wrapper element [\#1939](https://github.com/auth0/lock/pull/1939) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Remove javascript:void(0) from links that do not navigate [\#1938](https://github.com/auth0/lock/pull/1938) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Respect showTerms option for passwordless [\#1931](https://github.com/auth0/lock/pull/1931) ([saltukalakus](https://github.com/saltukalakus))
> Release 11.27.1

- src/field/email/email_pane.jsx
1- Fix the issue for the missing "use the corporate email" warning for HRD.
2- Fix the issue https://github.com/auth0/lock/issues/1952
1- After the fix the default behavior for multiple enterprise connections without an Auth0 DB.
https://user-images.githubusercontent.com/815705/104109319-b867ea00-52dd-11eb-9066-db137bab87ff.mov
2- Multiple enterprise connections along with the Auth0 DB.
https://user-images.githubusercontent.com/815705/104109322-c289e880-52dd-11eb-85c8-9aba7b9d96f4.mov
> Fix the email validation messages.

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Added**
- An option to hide username in signup view [\#1954](https://github.com/auth0/lock/pull/1954) ([saltukalakus](https://github.com/saltukalakus))
**Changed**
- Wording and spelling fixes to Bulgarian language file [\#1953](https://github.com/auth0/lock/pull/1953) ([maximnaidenov](https://github.com/maximnaidenov))
> Release v11.28.0

- package.json
- yarn.lock
upgrade trim to 0.0.3 to resolve security vulnerability found by Snyk security scan:
"this package are vulnerable to Regular Expression Denial of Service (ReDoS) via trim()" 
https://app.snyk.io/vuln/SNYK-JS-TRIM-1017038
> Upgrade trim version to fix security issue

- src/__tests__/ui/box/container.test.jsx
- src/ui/box/container.jsx
The passwordless login window does not honor the "mustAcceptTerms" flag set to true on Safari. A user is still able to hit the return key to send the magic link. (note that the submit button remains correctly disabled). This issue is not present on the latest version of chrome.
Lock relys on the submit button being disabled to prevent a user from submitting the form when they hit Enter.
This works on Chrome and forms with more than one field (which is why it only effects Passwordless), but Safari has a rule that states: If you have one text input Safari will submit the form regardless of a disabled submit button. If you have two text inputs or more Safari will not submit the form if the submit button is dsiabled.
We can manually prevent the form from submitting by adding an additional …
> Disable form submit manually for passwordless Safari

- css/index.styl
This PR removes the padding from the screen tabs control that was mistakenly
reintroduced in #1949.
Fixes #1970.
**Before**
**After**
> Remove padding from screen tabs

- README.md
This is simply changing a typo in the README from `assests` to `assets`.
> Fixes typo "assests" to "assets"

- README.md
- src/__tests__/core/remote_data.test.js
- src/core.js
- src/core/remote_data.js
- support/index.html
This PR adds a new event `ssodata fetched` that can be used to determine when the SSO Data endpoint is used as part of a call to `checkSession` (part of the API exposed by Auth0.js, which is used by Lock). An example of using this event might be to determine when the user has been silently authenticated, to then perform some other action.
Raised by internal service desk ticket.
> [SDK-2412] Add event for SSO data fetch

- src/field/captcha/recaptchav2.jsx
Move CSS override for `display` to the `render` function to fix recaptcha on sign-up.
- ESD-12716
> fix ESD-12716: move CSS display override to render function to fix recaptcha on sign-up

- CHANGELOG.md
- README.md
- bower.json
- package.json
[Full Changelog](https://github.com/auth0/lock/compare/v11.29.0...v11.29.1)
**Fixed**
- fix ESD-12716: move CSS display override to render function to fix recaptcha on sign-up [\#1983](https://github.com/auth0/lock/pull/1983) ([jfromaniello](https://github.com/jfromaniello))
> Release v11.29.1

- README.md
- src/__tests__/connection/passwordless/__snapshots__/passwordless.actions.test.js.snap
- src/__tests__/connection/passwordless/passwordless.actions.test.js
- src/__tests__/core/__snapshots__/index.test.js.snap
- src/connection/passwordless/actions.js
- src/core/index.js
This PR fixes an issue where custom/additional passwordless connections cannot be used from Lock.
Normally, only 1 email and 1 SMS passwordless connection can be created through the Manage dashboard. However, one can create additional passwordless connections using the Management API that use either the email or SMS strategy. Lock however has until now been hardcoded to always use `email` or `sms` connections and had no ability to use a custom passwordless connection that had been created.
This PR enables that scenario, behind a new option `useCustomPasswordlessConnection`. The flag is necessary as an opt-in, as this could otherwise be a breaking change for those who have additional passwordless connections set up in the dashboard but were unaware they were actually not being used.
To …
> [SDK-2383] Support custom passwordless connections

- src/__tests__/field/captcha.test.jsx
- src/__tests__/field/captcha/__snapshots__/recaptcha_enterprise.test.jsx.snap
- src/__tests__/field/captcha/recaptcha_enterprise.test.jsx
- src/__tests__/field/captcha/recaptchav2.test.jsx
- src/field/captcha/captcha_pane.jsx
- src/field/captcha/recaptcha.jsx
- test/captcha_signup.test.js
- Support enterprise recaptcha on lockjs.
[Corresponding PR on universal login prompts](https://github.com/auth0/universal-login-prompts/pull/1080)
No flow changes - allows a captcha provider of recaptcha_enterprise to render a recaptcha widget
> feat: recaptcha enterprise on lockjs

- package.json
- yarn.lock
This PR performs 2 dependency updates:
* Forcing `node-fetch` to resolve a vulnerability in the version used by React
`React > fbjs > isomorphic-fetch > node-fetch` ([link](https://app.snyk.io/vuln/SNYK-JS-NODEFETCH-674311))
* Update `auth0-js` to v9.16.2 (latest)
> Update auth0-js + node-fetch

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Changed**
- Update fa.js [\#2000](https://github.com/auth0/lock/pull/2000) ([alirezagit](https://github.com/alirezagit))
**Fixed**
- [SDK-2588] Avoid multiple simultaneous HTTP calls [\#1998](https://github.com/auth0/lock/pull/1998) ([frederikprijck](https://github.com/frederikprijck))
**Security**
- Update auth0-js + node-fetch [\#1996](https://github.com/auth0/lock/pull/1996) ([stevehobbsdev](https://github.com/stevehobbsdev))
- [SEC-687, SEC-700] For more information on this security release, please see [the release on GitHub](https://github.com/auth0/lock/releases/tag/v11.30.1).
[SDK-2588]: https://auth0team.atlassian.net/browse/SDK-2588
> Release 11.30.1

- src/__tests__/i18n.test.js
- src/core.js
- src/sanitizer.js
This PR adds a hook for [DOMPurify](https://github.com/cure53/DOMPurify) that allows elements that are sanitized
using `DOMPurify.sanitize` to have `target="_blank"` attributes, while also
adding `rel="noopener noreferrer"` to the same element to mitigate against
[Tab Nabbing](https://owasp.org/www-community/attacks/Reverse_Tabnabbing).
The implementation provided in [this example](https://github.com/cure53/DOMPurify/blob/main/demos/hooks-target-blank-demo.html) serves our purposes, and has been integrated vertabim.
Fixes `ESD-13941`
> [ESD-13941] Implement a DOMPurify hook to enable target attributes on links

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Changed**
- [ESD-13941] Implement a DOMPurify hook to enable target attributes on links [\#2006](https://github.com/auth0/lock/pull/2006) ([stevehobbsdev](https://github.com/stevehobbsdev))
[ESD-13941]: https://auth0team.atlassian.net/browse/ESD-13941
> Release 11.30.2

- src/i18n/nl.js
- letters to karakters
- sentence constructions
- English abbreviations for 'for example' like e.g., i.e., replaced by the Dutch bv.
- Some cases changed je to u (or uw). Most labels use the more formal u. In English both je and u are 'you'.
- Other changes
> SL - Updated Dutch translations

- scripts/ci.sh
This PR prevents the CI script from creating the release tag and modifying the release archive for Bower. Instead, that step will be performed manually in the short term until an alternative solution can be developed.
> Remove Bower publishing from Jenkins CI script

- CHANGELOG.md
- README.md
- bower.json
- package.json
**Changed**
[SDK-2708] Use `domain` value for client assets download instead of `cdn.*.auth0.com` [\#2029](https://github.com/auth0/lock/pull/2029) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
Inline `util.format` and replace usage of `global` for `window` [\#2030](https://github.com/auth0/lock/pull/2030) ([stevehobbsdev](https://github.com/stevehobbsdev))
[SDK-2708]: https://auth0team.atlassian.net/browse/SDK-2708
> Release 11.30.5

- package.json
- yarn.lock
Relates to: #2084 
This PR bumps the node-fetch dependency version from 2.6.6 to 2.6.7 to resolve a security vulnerability around forwarded headers within that release. See: https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7
> Security upgrade node-fetch to 2.6.7

- README.md
- package.json
- src/__tests__/core/web_api/__snapshots__/p2_api.test.js.snap
- src/core/web_api/p2_api.js
- yarn.lock
This PR updates auth0-js to include new functionality from Auth0.js, as well as supporting the `legacySameSiteCookie` option so that it can be passed through from Lock users.
https://github.com/auth0/auth0.js/pull/1232
> Update auth0-js and support legacySameSiteCookie option

- src/connection/passwordless/actions.js
In a previous PR #1981 a new parameter `useCustomPasswordlessConnection` was introduced for the Lock configuration. The reason for that change was that it is possible to create passwordless connections outside of the default `sms` and `email`. That PR mentions that it can be done via Management API, and it would seem that this includes Terraform (https://github.com/auth0/terraform-provider-auth0) where it seems to be the **only** way to use passwordless connections. 
This PR "completes" the above-mentioned PR where the connection parameter in `connection/passwordless/actions.js -> logIn` was still hard-coded to either `sms` or `email`
> More complete support for custom passwordless connections

- src/ui/box.js
ui box - div replaced by main
[Issue: HTML <main> Tag missing](https://github.com/auth0/lock/issues/2113)
> ui box - div replaced by main

- src/__tests__/connection/passwordless/__snapshots__/email_sent_confirmation.test.jsx.snap
- src/connection/passwordless/email_sent_confirmation.jsx
Don't always provide a function to `SuccessPane` instead pass the `closeHandler` variable so that `SuccessPane` can correctly distinguish whether to show the close buttong
This change updates the snapshot as `closable` is false in that test.
In order to test in the playground change `closable` to `false` and `passwordlessMethod` to `link` in `support/index.html`
> [ESD-22705] Don't pass function to ConfirmationPane unless closable is enabled

- src/engine/classic/sign_up_screen.jsx
When a user signs up, if they are logged in as part of the sign up process then the `success.logIn` message is shown rather than the `success.signUp` message as the `renderSignedInConfirmation` function is called first. So call `renderSignedUpConfirmation` first to ensure the correct message is shown
#2159
> [SDK-3657] Render sign up confirmation before sign in

- .circleci/config.yml
circleci config updated - docker image used: cimg/node:lts-browsers as it uses latest LTS node version
> chore(ci): use lts-browsers docker image

- .circleci/config.yml
- CHANGELOG.md
- README.md
- package.json
:warning: This is a **beta release** of Lock.js v12 that includes an upgrade to React 18, and should not be used in production. If you find any issues, please [submit a bug report](https://github.com/auth0/lock/issues/new?assignees=&labels=bug+report,v12-beta&template=report_a_bug.md&title=).
**Changed**
- Upgrade to React 18 [\#2209](https://github.com/auth0/lock/pull/2209) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Upgrade to Webpack 5, Jest 29, Babel 8 [\#2213](https://github.com/auth0/lock/pull/2213) ([stevehobbsdev](https://github.com/stevehobbsdev))
- bump dependencies to latest patch and fix typos [\#2210](https://github.com/auth0/lock/pull/2210) ([piwysocki](https://github.com/piwysocki))
---
This PR also includes a quick tweak to `.circleci/config.yml` that will allow …
> release v12.0.0-beta.0

- .circleci/config.yml
For now, Ship orb runs on Node 16.6.0 by default, we should configure it to run 18.12.1 for Lock.
> Update circle config to use latest ship-orb

- .circleci/config.yml
This is to fix [the build](https://app.circleci.com/pipelines/github/auth0/lock/1286/workflows/06857e5a-7ef2-49ac-a15d-79bca265e135/jobs/3438), which currently fails thanks to not being able to correctly determine whether the version being built has already been published. This bug is fixed in [this PR](https://github.com/auth0/ship-orb/pull/14).
> Use latest ship-orb in CI

- .circleci/config.yml
This cherry-picks the commit that updated the ship orb in #2234 and also configures circle to allow publishing to npm from the v11 branch
> Use latest ship orb, allow publish from v11 branch

- src/ui/box.js
A bug seems to have been recently introduced in v12:
This happens because
https://github.com/auth0/lock/blob/b708c308e55dcb4c93cc69664bd671e5e20761ed/src/ui/box.js#L59
assumes that if `this.modals[containerId]` is defined, `this.modals[containerId].component` is also defined. But this isn't always the case:
https://github.com/auth0/lock/blob/b708c308e55dcb4c93cc69664bd671e5e20761ed/src/ui/box.js#L42
> Fix when component is undefined

- support/design/index.html
- support/design/modal.html
- support/index.html
- support/playground/index.html
Setting user-scalable to 0 is against Web Content Accessibility Guidelines (WCAG). WCAG requires a minimum of 2× scaling
Changing the user-scalable="no" parameter from the content attribute of the <meta name="viewport"> element in order to allow zooming and ensuring the maximum-scale parameter is not less than 2.
https://dequeuniversity.com/rules/axe/4.6/meta-viewport
> Zooming and scaling must not be disabled

- EXAMPLES.md
Lock does not actually use `flashMessage` when specified in the constructor, and only uses the value when specified in `show()`. This PR corrects the documentation to reflect reality.
#2336
> docs: remove flashMessage docs from ui options

- src/ui/box/header.jsx
role="heading" attribute and aria-level="1" attribute added to WelcomeMessage heading.
It adds heading semantics to markup without the risk of breaking any styles.
This change resolves an issue in accessibility.
Header name and title appears to be heading for section of content, but is not marked as heading for screen reader users.
> WelcomeMessage header text marked as heading

- .circleci/config.yml
The tests on BS are very unreliable. Since we only run them on chrome, we should be okay to run them locally (on CI) using Karma instead.
> Do not run tests on browserstack

- .github/workflows/test.yml
This pull request updates the continuous integration workflow `test.yml`:
- Refine concurrency group specificity to improve efficiency. This cancels in-progress test runs when changes are committed to a pull request.
- Rename the test's `Run` step to `Build Package` for clarity to aid in filtering branch protection rules.
- Update checkout step to use `github.event.pull_request.head.sha` for `pull_request_target` (and `github.ref` for non-PR triggering events).
- Hardcode `node-version` to 18 rather than use an environment variable.
Updates based on internal feedback and conversations.
This pull request applies improvements to the continuous integration testing for the repository but does not add any additional tests.
> test: Improvements to CI Workflow

- .github/workflows/codeql.yml
- .github/workflows/publish.yml
- .github/workflows/semgrep.yml
- .github/workflows/snyk.yml
- .github/workflows/test.yml
This pull request updates our continuous integration workflows:
- Updated `pull_request` type triggers to use a narrower scope (avoids unnecessary runs.)
- Updated `push` branch triggers to be more concise (uses the `v*` wildcard.)
- Added concurrency check (cancels redundant in-progress runs.)
- Removed the `NODE_VERSION` environmental variable reference (hardcoded `18` value.)
- Updated to skip unnecessary runs on Dependabot PRs and re-runs on merge group queues.
- Updated name to use "Check for Vulnerabilities" for clarity in branch protection filters.
- Added concurrency check (cancels redundant in-progress runs.)
- Added workflow to trigger Snyk security checks.
We previously used webhooks to trigger these checks, but this method is incompatible with GitHub's merge queue feature. …
> test: Additional Improvements to CI Workflows

- css/index.styl
- src/__tests__/field/__snapshots__/custom_input.test.jsx.snap
- src/__tests__/field/custom_input.test.jsx
- src/field/custom_input.jsx
- src/ui/input/checkbox_input.jsx
- src/ui/input/input_wrap.jsx
- support/index.html
Wrap the `CheckBoxInput` in `InputWrapper` to allow for providing feedback as to what is wrong when a user clicks submit without the checkbox being selected. Below is an example of what this looks like, rather than highlight using a border like other fields we change the text to red.
**This image is outdated see below**
I did also see what it looked like without the red text, which is a little less obvious.
This is if we add a border around the entire element like the other components
I did also try a border/outline around the checkbox element but it looked bad due to inability to set the border radiu
Happy to change this up if there's a general preference that looks better.
Current status:
Invalid hint text provided
No invalid hint text provided
#2400
> Wrap CheckBoxInput in InputWrapper to provide visual feedback

- .github/workflows/publish.yml
Adds the npmjs registry url to setup-node as mentioned in the GitHub docs [for publishing npm packages](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry)
> Add registry-url to setup-node step in npm publish

- .github/workflows/test.yml
As we do not use any secrets, let's get rid of the `pull_request_target` trigger to simplify the CI.
> Remove pull_request_target trigger

- src/__tests__/field/captcha.test.jsx
- src/__tests__/field/captcha/__snapshots__/arkose.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/friendlyCaptcha.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/hcaptcha.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/recaptcha_enterprise.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/recaptchav2.test.jsx.snap
- src/__tests__/field/captcha/arkose.test.jsx
- src/__tests__/field/captcha/friendlyCaptcha.test.jsx
- src/__tests__/field/captcha/hcaptcha.test.jsx
- src/__tests__/field/captcha/recaptcha_enterprise.test.jsx
- src/__tests__/field/captcha/recaptchav2.test.jsx
- src/field/captcha/captcha_pane.jsx
- src/field/captcha/third_party_captcha.jsx
Adding support for Arkose catpcha. 
https://auth0team.atlassian.net/browse/IAMRISK-2603
https://github.com/auth0/lock/assets/121056923/35d25575-0822-4850-a499-e25ab5e0b800
> [IAMRISK-2603] Add support for Arkose

- .github/workflows/publish.yml
Adds registry-url to the setup-node step to ensure publishing will work in future
> Add registry-url to setup-node

- CHANGELOG.md
- README.md
- package.json
**Added**
- [IAMRISK-2603] Add support for Arkose [\#2455](https://github.com/auth0/lock/pull/2455) ([srijonsaha](https://github.com/srijonsaha))
[IAMRISK-2603]: https://auth0team.atlassian.net/browse/IAMRISK-2603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release v12.3.0

- test/captcha.corporate.test.js
The removed test seems to be [flakey in CI](https://github.com/auth0/lock/actions/runs/6454537714/job/17520286576?pr=2461) and it performs the same assertion as the test that ran before it. So combine these tests into one rather than fixing the second to wait
> Combine two tests to reduce flakeyness

- .github/dependabot.yml
Given that babel packages tend to be released together, use [dependabot groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) to handle them in one PR rather than individual PRs. 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> Group babel updates

- package.json
- yarn.lock
Upgrading auth0-js to solve a vulnerability with crypto-js [CVE-2023-46233](https://nvd.nist.gov/vuln/detail/CVE-2023-46233)
https://nvd.nist.gov/vuln/detail/CVE-2023-46233
#2479 
Ran unit tests. Checking with CI for integration test.
> Bump auth0-js to solve crypto-js vulnerability

- CHANGELOG.md
- package.json
**Security**
- Bump auth0-js to solve crypto-js vulnerability [\#2492](https://github.com/auth0/lock/pull/2492) ([frederikprijck](https://github.com/frederikprijck))
> Release v12.2.1

- css/index.styl
- src/__tests__/field/captcha.test.jsx
- src/__tests__/field/captcha/__snapshots__/auth0_v2.test.jsx.snap
- src/__tests__/field/captcha/auth0_v2.test.jsx
- src/__tests__/field/captcha/third_party_captcha.test.jsx
- src/connection/captcha.js
- src/connection/passwordless/actions.js
- src/core/index.js
- src/field/captcha/third_party_captcha.jsx
Added support for Auth0 v2 (Cloudflare turnstile) captcha provider.
https://auth0team.atlassian.net/browse/IAMRISK-2916
> [IAMRISK-2916] Added support for Auth0 v2 captcha provider

- src/__tests__/field/captcha/__snapshots__/arkose.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/auth0_v2.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/friendlyCaptcha.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/hcaptcha.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/recaptcha_enterprise.test.jsx.snap
- src/__tests__/field/captcha/__snapshots__/recaptchav2.test.jsx.snap
- src/__tests__/field/captcha/hcaptcha.test.jsx
- src/__tests__/field/captcha/third_party_captcha.test.jsx
- src/field/captcha/third_party_captcha.jsx
There's an issue with hcaptcha dissapearing and not reloading. There's a related thread [here](https://invisioncommunity.com/forums/topic/477281-hcaptcha-integration-not-working-as-expected/) that goes more in depth into the problem. The fix involves resetting the `window.hcaptcha` variable to force a reload.
[Ticket](https://auth0team.atlassian.net/browse/IAMRISK-3554)
> [IAMRISK-3554] hcaptcha bug fix

- package-lock.json
- package.json
- src/__tests__/connection/passwordless/__snapshots__/passwordless.test.js.snap
- src/__tests__/connection/passwordless/passwordless.test.js
- src/__tests__/engine/classic/__snapshots__/sign_up_pane.test.jsx.snap
- src/__tests__/engine/classic/sign_up_pane.test.jsx
- src/connection/captcha.js
- src/connection/database/actions.js
- src/connection/passwordless/index.js
- src/core/index.js
- src/core/remote_data.js
- src/core/web_api.js
- src/core/web_api/p2_api.js
- src/engine/classic/sign_up_pane.jsx
- test/captcha_signup.test.js
- test/helper/ui.js
* Uses Signup Captcha enforcement Policy for Signup instead of Login/Default enforcement policy (new capability)
* Uses reset_password enforcement Policy for reset_password (bug)
* Isolates calls for passwordless and reset password enforcement policy to specific flows instead of on Lock load (bug)
https://auth0team.atlassian.net/browse/IAMRISK-4032
https://auth0team.atlassian.net/browse/IAMRISK-4161
https://oktawiki.atlassian.net/wiki/spaces/IAMCA/pages/3113844770/Bot+Detection+Signup+Classic+UL+Testing+Documentation
> [IAMRISK-3539] Use signup classic endpoint for captcha

- package-lock.json
- package.json
- scripts/lang-audit.js
This PR resolves the security vulnerability SEC-2160 by removing the vulnerable `node-es-module-loader@0.3.8` dependency that was pulling in `core-js@2.6.12`.
1. **Removed vulnerable dependency**: Removed `node-es-module-loader@0.3.8` from devDependencies
2. **Updated lang-audit script**: Modified `scripts/lang-audit.js` to use native ES6 dynamic imports instead of the old module loader
3. **Leveraged existing infrastructure**: The script already uses the `esm` package, enabling native `import()` calls
- ✅ Eliminates the operational risk from `core-js@2.6.12`
- ✅ Maintains all existing functionality
- ✅ All 68 test suites pass (401 tests total)
- ✅ The `i18n:validate` script continues to work correctly
- All existing tests pass
- The i18n validation script functions correctly with 100% …
> security: Remove vulnerable node-es-module-loader dependency (SEC-2160)

- src/connection/social/index.js
This PR fixes a small bug where marketplace social connections are not showing the `displayName` correctly and defaults to Strategy ID instead.
Before changes (notice `sign-in-with-slack`:
After changes (fixed, login now showing `Slack`):
> Fix: social connection names not showing displayName correctly

- package-lock.json
- package.json
- src/connection/social/index.js
- **Bump `fsevents` to latest** (`2.3.3` → `^2.3.3`) in `package.json` and `package-lock.json`  
- Addresses compatibility issues with Node 18+ and fixes the sandbox-compatibility error in CI  
- **Lockfile cleanup**  
- Regenerated `package-lock.json` to remove outdated entries and avoid conflicts  
- Security ticket: [SEC-2025-0421](https://support.auth0.com/tickets/SEC-2025-0421)  
- Resolves security vulnerability SEC-2161
- Related GitHub issue: https://github.com/auth0/lock/issues/2609
> security: bump fsevents to latest(SEC- 2161)

- src/__tests__/core/remote_data.test.js
- src/core/actions.js
- src/core/remote_data.js
- src/field/captcha/captcha_pane.jsx
- support/design/index.html
- test/captcha_initial_signup.test.js
When a custom login page that uses Lock.js is initialized with the initialScreen: "signUp" value, we expect the Lock widget to render the signup prompt first. We also expect the initialization logic to render a CAPTCHA widget if a CAPTCHA is expected to be completed for signups.
The initialization does not render the CAPTCHA widget accordingly. The end-user might encounter an error if they submit the signup prompt without having solved a captcha.
Before fix: Captcha Required, but does not render when `initialScreen` is set to 'signUp'
After fix: Captcha required and is rendered when `initialScreen` is set to 'signUp'
https://github.com/user-attachments/assets/a7804a31-9e25-4cc6-b2ca-a380bacab0c9
https://github.com/user-attachments/assets/7669f00f-0380-46c1-8e61-6526b564543b
> fix: captcha not rendering for initial signup screen in classic login 
